'use strict';
var express = require('express');
var router = express.Router();
var app = express();
var path = require('path');
//var pthv = require('./pthv');

/* GET home page. */

router.get('/', (req, res) => {
    console.log("in here a");

    console.log(req.path);
    console.log(req.params);
    console.log(req.params.useridname);
    // app.use('/pthv/:useridname', pthv);
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify(

        [
            {
                "navMid": 1.17,
                "navPerShare": null,
                "rsi": 61.3,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "CCL",
                "stockName": "CARNIVAL",
                "profit": -6902,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": 1,
                "percentUp": 16.95,
                "weekPercentUp": null,
                "marketCapitalisation": 17036,
                "day": "3121522",
                "week": "3121522",
                "years": "CCL",
                "sedol": "GB0031215220",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 2.29,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 1.17,
                "navPerShare": null,
                "rsi": 55.28,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "IAG",
                "stockName": "INTL CONSOL A",
                "profit": -6154,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": 0,
                "percentUp": 10.99,
                "weekPercentUp": null,
                "marketCapitalisation": 7275,
                "day": "7754201",
                "week": "7754201",
                "years": "IAG",
                "sedol": "ES0177542018",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.71,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 0.51,
                "navPerShare": null,
                "rsi": 56.9,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "EZJ",
                "stockName": "EASYJET",
                "profit": -858,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": 1,
                "percentUp": 10.82,
                "weekPercentUp": null,
                "marketCapitalisation": 4268,
                "day": "B7KR2P8",
                "week": "B7KR2P8",
                "years": "EZJ",
                "sedol": "GB00B7KR2P84",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.16,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 0.89,
                "navPerShare": null,
                "rsi": 54.89,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "WTB",
                "stockName": "WHITBREAD",
                "profit": -907,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": 0,
                "percentUp": 8.23,
                "weekPercentUp": null,
                "marketCapitalisation": 6058,
                "day": "B1KJJ40",
                "week": "B1KJJ40",
                "years": "WTB",
                "sedol": "GB00B1KJJ408",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.77,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": -0.29,
                "navPerShare": null,
                "rsi": 57.79,
                "midPrice": null,
                "dividend": 1,
                "tickerSymbol": "MRO",
                "stockName": "MELROSE IND",
                "profit": -526,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 5.78,
                "techSum": 1,
                "percentUp": 7.49,
                "weekPercentUp": null,
                "marketCapitalisation": 6928,
                "day": "BNR5MZ7",
                "week": "BNR5MZ7",
                "years": "MRO",
                "sedol": "GB00BNR5MZ78",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "General Indus"
            },
            {
                "navMid": -0.06,
                "navPerShare": null,
                "rsi": 44.8,
                "midPrice": null,
                "dividend": 1.31,
                "tickerSymbol": "RTO",
                "stockName": "RENTOKIL INIT",
                "profit": 186,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 41.41,
                "techSum": -1,
                "percentUp": 7.11,
                "weekPercentUp": null,
                "marketCapitalisation": 10676,
                "day": "B082RF1",
                "week": "B082RF1",
                "years": "RTO",
                "sedol": "GB00B082RF11",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.69,
                "bullAdvice": "2021-12-20 BUY",
                "sector": "Industrial Su"
            },
            {
                "navMid": 0,
                "navPerShare": null,
                "rsi": 55,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "IHG",
                "stockName": "INTERCON. HOT",
                "profit": -203,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": 1,
                "percentUp": 7.09,
                "weekPercentUp": null,
                "marketCapitalisation": 8736,
                "day": "BHJYC05",
                "week": "BHJYC05",
                "years": "IHG",
                "sedol": "GB00BHJYC057",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.69,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 0,
                "navPerShare": null,
                "rsi": 47.2,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RR.",
                "stockName": "ROLLS-ROYCE H",
                "profit": -1315,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 3.09,
                "techSum": 1,
                "percentUp": 7.02,
                "weekPercentUp": null,
                "marketCapitalisation": 10177,
                "day": "B63H849",
                "week": "B63H849",
                "years": "RR.",
                "sedol": "GB00B63H8491",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Aerospace and"
            },
            {
                "navMid": 0.39,
                "navPerShare": null,
                "rsi": 46.25,
                "midPrice": null,
                "dividend": 0.14,
                "tickerSymbol": "JD.",
                "stockName": "JD SPORTS",
                "profit": 246,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 25.54,
                "techSum": 0,
                "percentUp": 7.02,
                "weekPercentUp": null,
                "marketCapitalisation": 10904,
                "day": "BYX91H5",
                "week": "BYX91H5",
                "years": "JD.",
                "sedol": "GB00BYX91H57",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.18,
                "bullAdvice": "2021-12-20 BUY",
                "sector": "Retailers"
            },
            {
                "navMid": -0.05,
                "navPerShare": null,
                "rsi": 63.05,
                "midPrice": null,
                "dividend": 0.85,
                "tickerSymbol": "CPG",
                "stockName": "COMPASS GROUP",
                "profit": 357,
                "cash": null,
                "exDividend": "2022-01-20",
                "netNet": 0,
                "peRatio": 81.92,
                "techSum": 1,
                "percentUp": 5.24,
                "weekPercentUp": null,
                "marketCapitalisation": 29375,
                "day": "BD6K457",
                "week": "BD6K457",
                "years": "CPG",
                "sedol": "GB00BD6K4575",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.31,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Consumer Serv"
            },
            {
                "navMid": 0.58,
                "navPerShare": null,
                "rsi": 68.1,
                "midPrice": null,
                "dividend": 4.73,
                "tickerSymbol": "TW.",
                "stockName": "TAYLOR WIMPEY",
                "profit": 674,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 13.19,
                "techSum": 1,
                "percentUp": 5.11,
                "weekPercentUp": null,
                "marketCapitalisation": 6390,
                "day": "0878230",
                "week": "0878230",
                "years": "TW.",
                "sedol": "GB0008782301",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-11-24 BUY",
                "sector": "Household Goo"
            },
            {
                "navMid": 0.03,
                "navPerShare": null,
                "rsi": 57,
                "midPrice": null,
                "dividend": 1.07,
                "tickerSymbol": "AVV",
                "stockName": "AVEVA GRP",
                "profit": 25,
                "cash": null,
                "exDividend": "2022-01-06",
                "netNet": 0,
                "peRatio": 0,
                "techSum": 1,
                "percentUp": 5,
                "weekPercentUp": null,
                "marketCapitalisation": 10287,
                "day": "BBG9VN7",
                "week": "BBG9VN7",
                "years": "AVV",
                "sedol": "GB00BBG9VN75",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.01,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Software and "
            },
            {
                "navMid": -0.05,
                "navPerShare": null,
                "rsi": 69.3,
                "midPrice": null,
                "dividend": 2.09,
                "tickerSymbol": "SGE",
                "stockName": "SAGE GRP.",
                "profit": 0,
                "cash": null,
                "exDividend": "2022-01-13",
                "netNet": 0,
                "peRatio": 32.3,
                "techSum": 2,
                "percentUp": 4.36,
                "weekPercentUp": null,
                "marketCapitalisation": 8672,
                "day": "B8C3BL0",
                "week": "B8C3BL0",
                "years": "SGE",
                "sedol": "GB00B8C3BL03",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 2.24,
                "bullAdvice": "2021-12-01 BUY",
                "sector": "Software and "
            },
            {
                "navMid": 1.09,
                "navPerShare": null,
                "rsi": 52.28,
                "midPrice": null,
                "dividend": 2.6,
                "tickerSymbol": "LLOY",
                "stockName": "LLOYDS GRP.",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 7.27,
                "techSum": 1,
                "percentUp": 4.35,
                "weekPercentUp": null,
                "marketCapitalisation": 33688,
                "day": "0870612",
                "week": "0870612",
                "years": "LLOY",
                "sedol": "GB0008706128",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Banks"
            },
            {
                "navMid": 0.47,
                "navPerShare": null,
                "rsi": 43,
                "midPrice": null,
                "dividend": 3.51,
                "tickerSymbol": "JMAT",
                "stockName": "JOHNSON MATTH",
                "profit": 205,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 25.93,
                "techSum": 0,
                "percentUp": 4.13,
                "weekPercentUp": null,
                "marketCapitalisation": 3960,
                "day": "BZ4BQC7",
                "week": "BZ4BQC7",
                "years": "JMAT",
                "sedol": "GB00BZ4BQC70",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.61,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Chemicals"
            },
            {
                "navMid": 0.05,
                "navPerShare": null,
                "rsi": 66,
                "midPrice": null,
                "dividend": 2.99,
                "tickerSymbol": "STJ",
                "stockName": "ST.JAMES'S PL",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 44.3,
                "techSum": 2,
                "percentUp": 4.12,
                "weekPercentUp": null,
                "marketCapitalisation": 9038,
                "day": "0766937",
                "week": "0766937",
                "years": "STJ",
                "sedol": "GB0007669376",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.13,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Life Insuranc"
            },
            {
                "navMid": 0.34,
                "navPerShare": null,
                "rsi": 57,
                "midPrice": null,
                "dividend": 8.3,
                "tickerSymbol": "PSN",
                "stockName": "PERSIMMON",
                "profit": 638,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 11.45,
                "techSum": 2,
                "percentUp": 3.92,
                "weekPercentUp": null,
                "marketCapitalisation": 9034,
                "day": "0682538",
                "week": "0682538",
                "years": "PSN",
                "sedol": "GB0006825383",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.65,
                "bullAdvice": "2021-12-15 SELL",
                "sector": "Household Goo"
            },
            {
                "navMid": 0.01,
                "navPerShare": null,
                "rsi": 64.5,
                "midPrice": null,
                "dividend": 0.95,
                "tickerSymbol": "RMV",
                "stockName": "RIGHTMOVE",
                "profit": 110,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 44.75,
                "techSum": 2,
                "percentUp": 3.46,
                "weekPercentUp": null,
                "marketCapitalisation": 6691,
                "day": "BGDT3G2",
                "week": "BGDT3G2",
                "years": "RMV",
                "sedol": "GB00BGDT3G23",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.82,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Software and "
            },
            {
                "navMid": 0.08,
                "navPerShare": null,
                "rsi": 76,
                "midPrice": null,
                "dividend": 1.35,
                "tickerSymbol": "FERG",
                "stockName": "FERGUSON",
                "profit": 1217,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": 2,
                "percentUp": 3.32,
                "weekPercentUp": null,
                "marketCapitalisation": 28910,
                "day": "BJVNSS4",
                "week": "BJVNSS4",
                "years": "FERG",
                "sedol": "JE00BJVNSS43",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.55,
                "bullAdvice": "2021-12-07 BUY",
                "sector": "Industrial Su"
            },
            {
                "navMid": -0.16,
                "navPerShare": null,
                "rsi": 50.54,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ITV",
                "stockName": "ITV",
                "profit": 285,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 12.26,
                "techSum": 0,
                "percentUp": 3.26,
                "weekPercentUp": null,
                "marketCapitalisation": 4474,
                "day": "3398649",
                "week": "3398649",
                "years": "ITV",
                "sedol": "GB0033986497",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.9,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Media"
            },
            {
                "navMid": 0.08,
                "navPerShare": null,
                "rsi": 55.8,
                "midPrice": null,
                "dividend": 2.12,
                "tickerSymbol": "SN.",
                "stockName": "SMITH&NEPHEW",
                "profit": 470,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 27.17,
                "techSum": 1,
                "percentUp": 3.23,
                "weekPercentUp": null,
                "marketCapitalisation": 11252,
                "day": "0922320",
                "week": "0922320",
                "years": "SN.",
                "sedol": "GB0009223206",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.55,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Medical Equip"
            },
            {
                "navMid": -0.25,
                "navPerShare": null,
                "rsi": 62.5,
                "midPrice": null,
                "dividend": 2.37,
                "tickerSymbol": "WPP",
                "stockName": "WPP",
                "profit": -2974,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": 2,
                "percentUp": 3.21,
                "weekPercentUp": null,
                "marketCapitalisation": 12943,
                "day": "B8KF9B4",
                "week": "B8KF9B4",
                "years": "WPP",
                "sedol": "JE00B8KF9B49",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.98,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Media"
            },
            {
                "navMid": 1.35,
                "navPerShare": null,
                "rsi": 57.9,
                "midPrice": null,
                "dividend": 2.65,
                "tickerSymbol": "NWG",
                "stockName": "ROYAL BANK SC",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.01,
                "peRatio": 11.16,
                "techSum": 1,
                "percentUp": 3.19,
                "weekPercentUp": null,
                "marketCapitalisation": 25531,
                "day": "B7T7721",
                "week": "B7T7721",
                "years": "NWG",
                "sedol": "GB00B7T77214",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Banks"
            },
            {
                "navMid": 1.26,
                "navPerShare": null,
                "rsi": 51.2,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RDSB",
                "stockName": "RDS 'B'",
                "profit": -16906,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": 1,
                "percentUp": 3.17,
                "weekPercentUp": null,
                "marketCapitalisation": 126386,
                "day": "B03MM40",
                "week": "B03MM40",
                "years": "RDSB",
                "sedol": "GB00B03MM408",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.12,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Oil, Gas and "
            },
            {
                "navMid": 1.26,
                "navPerShare": null,
                "rsi": 51.4,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RDSA",
                "stockName": "RDS 'A'",
                "profit": -16906,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": 1,
                "percentUp": 3.1,
                "weekPercentUp": null,
                "marketCapitalisation": 126479,
                "day": "B03MLX2",
                "week": "B03MLX2",
                "years": "RDSA",
                "sedol": "GB00B03MLX29",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.21,
                "bullAdvice": "2021-12-23 BUY",
                "sector": "Oil, Gas and "
            },
            {
                "navMid": -0.28,
                "navPerShare": null,
                "rsi": 46.7,
                "midPrice": null,
                "dividend": 4.44,
                "tickerSymbol": "BA.",
                "stockName": "BAE SYSTEMS P",
                "profit": 1476,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 9.92,
                "techSum": -1,
                "percentUp": 3.02,
                "weekPercentUp": null,
                "marketCapitalisation": 17267,
                "day": "0263494",
                "week": "0263494",
                "years": "BA.",
                "sedol": "GB0002634946",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.37,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Aerospace and"
            },
            {
                "navMid": -0.7,
                "navPerShare": null,
                "rsi": 63.98,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "CNA",
                "stockName": "CENTRICA",
                "profit": -274,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 2.54,
                "techSum": 1,
                "percentUp": 2.99,
                "weekPercentUp": null,
                "marketCapitalisation": 4057,
                "day": "B033F22",
                "week": "B033F22",
                "years": "CNA",
                "sedol": "GB00B033F229",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Gas, Water an"
            },
            {
                "navMid": 0.53,
                "navPerShare": null,
                "rsi": 61.6,
                "midPrice": null,
                "dividend": 3.98,
                "tickerSymbol": "BDEV",
                "stockName": "BARRATT DEVEL",
                "profit": 660,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 11.54,
                "techSum": 1,
                "percentUp": 2.93,
                "weekPercentUp": null,
                "marketCapitalisation": 7552,
                "day": "0081180",
                "week": "0081180",
                "years": "BDEV",
                "sedol": "GB0000811801",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.07,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Household Goo"
            },
            {
                "navMid": 0.04,
                "navPerShare": null,
                "rsi": 47,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "NXT",
                "stockName": "NEXT PLC",
                "profit": 287,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 17.5,
                "techSum": -1,
                "percentUp": 2.86,
                "weekPercentUp": null,
                "marketCapitalisation": 10561,
                "day": "3208986",
                "week": "3208986",
                "years": "NXT",
                "sedol": "GB0032089863",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.01,
                "bullAdvice": "2021-12-10 SELL",
                "sector": "Retailers"
            },
            {
                "navMid": 0.52,
                "navPerShare": null,
                "rsi": 58.6,
                "midPrice": null,
                "dividend": 6.01,
                "tickerSymbol": "LGEN",
                "stockName": "LEGAL&GEN.",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 7.83,
                "techSum": 2,
                "percentUp": 2.78,
                "weekPercentUp": null,
                "marketCapitalisation": 17714,
                "day": "0560399",
                "week": "0560399",
                "years": "LGEN",
                "sedol": "GB0005603997",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.16,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Life Insuranc"
            },
            {
                "navMid": 1.8,
                "navPerShare": null,
                "rsi": 52.44,
                "midPrice": null,
                "dividend": 1.6,
                "tickerSymbol": "BARC",
                "stockName": "BARCLAYS",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.01,
                "peRatio": 6.01,
                "techSum": 1,
                "percentUp": 2.77,
                "weekPercentUp": null,
                "marketCapitalisation": 31397,
                "day": "3134865",
                "week": "3134865",
                "years": "BARC",
                "sedol": "GB0031348658",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.07,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Banks"
            },
            {
                "navMid": -0.65,
                "navPerShare": null,
                "rsi": 55.1,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "INF",
                "stockName": "INFORMA",
                "profit": -1042,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": 1,
                "percentUp": 2.59,
                "weekPercentUp": null,
                "marketCapitalisation": 7732,
                "day": "BMJ6DW5",
                "week": "BMJ6DW5",
                "years": "INF",
                "sedol": "GB00BMJ6DW54",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.97,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Media"
            },
            {
                "navMid": 0,
                "navPerShare": null,
                "rsi": 57,
                "midPrice": null,
                "dividend": 0.58,
                "tickerSymbol": "HLMA",
                "stockName": "HALMA",
                "profit": 203,
                "cash": null,
                "exDividend": "2021-12-23",
                "netNet": 0,
                "peRatio": 45.47,
                "techSum": 1,
                "percentUp": 2.59,
                "weekPercentUp": null,
                "marketCapitalisation": 11928,
                "day": "0405207",
                "week": "0405207",
                "years": "HLMA",
                "sedol": "GB0004052071",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.6,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Electronic an"
            },
            {
                "navMid": 0,
                "navPerShare": null,
                "rsi": 55.72,
                "midPrice": null,
                "dividend": 9.22,
                "tickerSymbol": "MNG",
                "stockName": "M&G PLC",
                "profit": -55,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 84.93,
                "techSum": 1,
                "percentUp": 2.58,
                "weekPercentUp": null,
                "marketCapitalisation": 5170,
                "day": "BKFB1C6",
                "week": "BKFB1C6",
                "years": "MNG",
                "sedol": "GB00BKFB1C65",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Investment Ba"
            },
            {
                "navMid": 0.28,
                "navPerShare": null,
                "rsi": 62,
                "midPrice": null,
                "dividend": 2.13,
                "tickerSymbol": "CRH",
                "stockName": "CRH",
                "profit": 875,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 27.26,
                "techSum": 2,
                "percentUp": 2.49,
                "weekPercentUp": null,
                "marketCapitalisation": 29961,
                "day": "0182704",
                "week": "0182704",
                "years": "CRH",
                "sedol": "IE0001827041",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.68,
                "bullAdvice": "2021-12-07 BUY",
                "sector": "Construction "
            },
            {
                "navMid": 0.13,
                "navPerShare": null,
                "rsi": 63.6,
                "midPrice": null,
                "dividend": 2.39,
                "tickerSymbol": "SMIN",
                "stockName": "SMITHS GROUP",
                "profit": 156,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 38.61,
                "techSum": 1,
                "percentUp": 2.43,
                "weekPercentUp": null,
                "marketCapitalisation": 6209,
                "day": "B1WY233",
                "week": "B1WY233",
                "years": "SMIN",
                "sedol": "GB00B1WY2338",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.06,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "General Indus"
            },
            {
                "navMid": 0.06,
                "navPerShare": null,
                "rsi": 55.65,
                "midPrice": null,
                "dividend": 1.35,
                "tickerSymbol": "BT.A",
                "stockName": "BT GROUP",
                "profit": 1472,
                "cash": null,
                "exDividend": "2021-12-30",
                "netNet": 0,
                "peRatio": 16.55,
                "techSum": 1,
                "percentUp": 2.4,
                "weekPercentUp": null,
                "marketCapitalisation": 16927,
                "day": "3091357",
                "week": "3091357",
                "years": "BT.A",
                "sedol": "GB0030913577",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.17,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Telecommunica"
            },
            {
                "navMid": 0.14,
                "navPerShare": null,
                "rsi": 46,
                "midPrice": null,
                "dividend": 3.04,
                "tickerSymbol": "BRBY",
                "stockName": "BURBERRY GRP",
                "profit": 376,
                "cash": null,
                "exDividend": "2021-12-16",
                "netNet": 0,
                "peRatio": 15.34,
                "techSum": -1,
                "percentUp": 2.39,
                "weekPercentUp": null,
                "marketCapitalisation": 7182,
                "day": "3174300",
                "week": "3174300",
                "years": "BRBY",
                "sedol": "GB0031743007",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.23,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Personal Good"
            },
            {
                "navMid": 0.21,
                "navPerShare": null,
                "rsi": 51,
                "midPrice": null,
                "dividend": 2.64,
                "tickerSymbol": "ICP",
                "stockName": "INT.CAP.GRP",
                "profit": 3900,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 12.65,
                "techSum": 1,
                "percentUp": 2.35,
                "weekPercentUp": null,
                "marketCapitalisation": 6357,
                "day": "BYT1DJ1",
                "week": "BYT1DJ1",
                "years": "ICP",
                "sedol": "GB00BYT1DJ19",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.52,
                "bullAdvice": "2021-12-23 BUY",
                "sector": "Investment Ba"
            },
            {
                "navMid": 0.53,
                "navPerShare": null,
                "rsi": 61.6,
                "midPrice": null,
                "dividend": 5.86,
                "tickerSymbol": "AAL",
                "stockName": "ANGLO AMERICA",
                "profit": 1629,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 7.49,
                "techSum": 2,
                "percentUp": 2.34,
                "weekPercentUp": null,
                "marketCapitalisation": 40839,
                "day": "B1XZS82",
                "week": "B1XZS82",
                "years": "AAL",
                "sedol": "GB00B1XZS820",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.62,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Industrial Me"
            },
            {
                "navMid": -0.1,
                "navPerShare": null,
                "rsi": 56.71,
                "midPrice": null,
                "dividend": 1.02,
                "tickerSymbol": "EXPN",
                "stockName": "EXPERIAN",
                "profit": 615,
                "cash": null,
                "exDividend": "2022-01-06",
                "netNet": 0,
                "peRatio": 44.54,
                "techSum": 1,
                "percentUp": 2.26,
                "weekPercentUp": null,
                "marketCapitalisation": 32964,
                "day": "B19NLV4",
                "week": "B19NLV4",
                "years": "EXPN",
                "sedol": "GB00B19NLV48",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.23,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Industrial Su"
            },
            {
                "navMid": 0.68,
                "navPerShare": null,
                "rsi": 55.04,
                "midPrice": null,
                "dividend": 2.33,
                "tickerSymbol": "GLEN",
                "stockName": "GLENCORE",
                "profit": -1484,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 33.44,
                "techSum": 1,
                "percentUp": 2.18,
                "weekPercentUp": null,
                "marketCapitalisation": 49233,
                "day": "B4T3BW6",
                "week": "B4T3BW6",
                "years": "GLEN",
                "sedol": "JE00B4T3BW64",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.27,
                "bullAdvice": "2021-12-15 SELL",
                "sector": "Industrial Me"
            },
            {
                "navMid": 0.44,
                "navPerShare": null,
                "rsi": 53.99,
                "midPrice": null,
                "dividend": 2.01,
                "tickerSymbol": "REL",
                "stockName": "RELX",
                "profit": 1224,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 34.3,
                "techSum": 2,
                "percentUp": 2.09,
                "weekPercentUp": null,
                "marketCapitalisation": 45892,
                "day": "B2B0DG9",
                "week": "B2B0DG9",
                "years": "REL",
                "sedol": "GB00B2B0DG97",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.19,
                "bullAdvice": "2021-12-07 BUY",
                "sector": "Media"
            },
            {
                "navMid": 0.49,
                "navPerShare": null,
                "rsi": 56,
                "midPrice": null,
                "dividend": 1.34,
                "tickerSymbol": "ABF",
                "stockName": "A.B.FOOD",
                "profit": 478,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 32.89,
                "techSum": 1,
                "percentUp": 2.08,
                "weekPercentUp": null,
                "marketCapitalisation": 15754,
                "day": "0673123",
                "week": "0673123",
                "years": "ABF",
                "sedol": "GB0006731235",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.7,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Food Producer"
            },
            {
                "navMid": 0.51,
                "navPerShare": null,
                "rsi": 64,
                "midPrice": null,
                "dividend": 2.63,
                "tickerSymbol": "BKG",
                "stockName": "BERKELEY GP.H",
                "profit": 423,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 11.97,
                "techSum": 1,
                "percentUp": 2.04,
                "weekPercentUp": null,
                "marketCapitalisation": 5369,
                "day": "BLJNXL8",
                "week": "BLJNXL8",
                "years": "BKG",
                "sedol": "GB00BLJNXL82",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.27,
                "bullAdvice": "2021-12-01 BUY",
                "sector": "Household Goo"
            },
            {
                "navMid": 1.11,
                "navPerShare": null,
                "rsi": 42.3,
                "midPrice": null,
                "dividend": 3.86,
                "tickerSymbol": "SBRY",
                "stockName": "SAINSBURY(J)",
                "profit": -287,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 23.2,
                "techSum": -1,
                "percentUp": 2.04,
                "weekPercentUp": null,
                "marketCapitalisation": 6413,
                "day": "B019KW7",
                "week": "B019KW7",
                "years": "SBRY",
                "sedol": "GB00B019KW72",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.37,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Personal Care"
            },
            {
                "navMid": -0.07,
                "navPerShare": null,
                "rsi": 52,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "FLTR",
                "stockName": "FLUTTER ENT",
                "profit": 38,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": 0,
                "percentUp": 2.03,
                "weekPercentUp": null,
                "marketCapitalisation": 20021,
                "day": "BWT6H89",
                "week": "BWT6H89",
                "years": "FLTR",
                "sedol": "IE00BWT6H894",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.2,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 3.21,
                "navPerShare": null,
                "rsi": 53,
                "midPrice": null,
                "dividend": 1.23,
                "tickerSymbol": "STAN",
                "stockName": "STAND.CHART.",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.02,
                "peRatio": 10.7,
                "techSum": 0,
                "percentUp": 1.97,
                "weekPercentUp": null,
                "marketCapitalisation": 13588,
                "day": "0408284",
                "week": "0408284",
                "years": "STAN",
                "sedol": "GB0004082847",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.34,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Banks"
            },
            {
                "navMid": -0.05,
                "navPerShare": null,
                "rsi": 57,
                "midPrice": null,
                "dividend": 1.88,
                "tickerSymbol": "BNZL",
                "stockName": "BUNZL",
                "profit": 430,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 21.36,
                "techSum": 2,
                "percentUp": 1.88,
                "weekPercentUp": null,
                "marketCapitalisation": 9788,
                "day": "B0744B3",
                "week": "B0744B3",
                "years": "BNZL",
                "sedol": "GB00B0744B38",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.33,
                "bullAdvice": "2021-12-23 BUY",
                "sector": "General Indus"
            },
            {
                "navMid": 0.01,
                "navPerShare": null,
                "rsi": 48,
                "midPrice": null,
                "dividend": 0.79,
                "tickerSymbol": "SPX",
                "stockName": "SPIRAX-SARCO",
                "profit": 174,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 56.17,
                "techSum": -1,
                "percentUp": 1.83,
                "weekPercentUp": null,
                "marketCapitalisation": 11585,
                "day": "BWFGQN1",
                "week": "BWFGQN1",
                "years": "SPX",
                "sedol": "GB00BWFGQN14",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.18,
                "bullAdvice": "2021-12-23 BUY",
                "sector": "Industrial En"
            },
            {
                "navMid": -0.02,
                "navPerShare": null,
                "rsi": 59,
                "midPrice": null,
                "dividend": 1.88,
                "tickerSymbol": "ITRK",
                "stockName": "INTERTEK GROU",
                "profit": 247,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 34.14,
                "techSum": 1,
                "percentUp": 1.78,
                "weekPercentUp": null,
                "marketCapitalisation": 9074,
                "day": "3163836",
                "week": "3163836",
                "years": "ITRK",
                "sedol": "GB0031638363",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.11,
                "bullAdvice": "2021-12-15 BUY",
                "sector": "Industrial Su"
            },
            {
                "navMid": 0.77,
                "navPerShare": null,
                "rsi": 61.1,
                "midPrice": null,
                "dividend": 4.88,
                "tickerSymbol": "AV.",
                "stockName": "AVIVA",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 9.39,
                "techSum": 1,
                "percentUp": 1.74,
                "weekPercentUp": null,
                "marketCapitalisation": 15433,
                "day": "0216238",
                "week": "0216238",
                "years": "AV.",
                "sedol": "GB0002162385",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-14 BUY",
                "sector": "Life Insuranc"
            },
            {
                "navMid": 1.55,
                "navPerShare": null,
                "rsi": 61.34,
                "midPrice": null,
                "dividend": 4,
                "tickerSymbol": "LAND",
                "stockName": "LAND SECS.",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.04,
                "peRatio": 0,
                "techSum": 1,
                "percentUp": 1.74,
                "weekPercentUp": null,
                "marketCapitalisation": 5660,
                "day": "BYW0PQ6",
                "week": "BYW0PQ6",
                "years": "LAND",
                "sedol": "GB00BYW0PQ60",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.27,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Real Estate I"
            },
            {
                "navMid": 0.23,
                "navPerShare": null,
                "rsi": 54.98,
                "midPrice": null,
                "dividend": 5.02,
                "tickerSymbol": "SSE",
                "stockName": "SSE",
                "profit": 2246,
                "cash": null,
                "exDividend": "2022-01-13",
                "netNet": 0,
                "peRatio": 6.66,
                "techSum": 2,
                "percentUp": 1.62,
                "weekPercentUp": null,
                "marketCapitalisation": 17425,
                "day": "0790873",
                "week": "0790873",
                "years": "SSE",
                "sedol": "GB0007908733",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.06,
                "bullAdvice": "2021-12-20 BUY",
                "sector": "Electricity"
            },
            {
                "navMid": 0.28,
                "navPerShare": null,
                "rsi": 52.01,
                "midPrice": null,
                "dividend": 7.42,
                "tickerSymbol": "PHNX",
                "stockName": "PHOENIX GRP H",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 0,
                "techSum": 1,
                "percentUp": 1.48,
                "weekPercentUp": null,
                "marketCapitalisation": 6489,
                "day": "BGXQNP2",
                "week": "BGXQNP2",
                "years": "PHNX",
                "sedol": "GB00BGXQNP29",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.39,
                "bullAdvice": null,
                "sector": "Life Insuranc"
            },
            {
                "navMid": -0.03,
                "navPerShare": null,
                "rsi": 57,
                "midPrice": null,
                "dividend": 1.06,
                "tickerSymbol": "AUTO",
                "stockName": "AUTO TRAD",
                "profit": 128,
                "cash": null,
                "exDividend": "2022-01-06",
                "netNet": -0.06,
                "peRatio": 35.74,
                "techSum": 1,
                "percentUp": 1.4,
                "weekPercentUp": null,
                "marketCapitalisation": 6868,
                "day": "BVYVFW2",
                "week": "BVYVFW2",
                "years": "AUTO",
                "sedol": "GB00BVYVFW23",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.04,
                "bullAdvice": "2021-12-13 BUY",
                "sector": "Software and "
            },
            {
                "navMid": -0.15,
                "navPerShare": null,
                "rsi": 55.46,
                "midPrice": null,
                "dividend": 2.35,
                "tickerSymbol": "AZN",
                "stockName": "ASTRAZENECA",
                "profit": 2492,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 90.7,
                "techSum": 1,
                "percentUp": 1.32,
                "weekPercentUp": null,
                "marketCapitalisation": 133398,
                "day": "0989529",
                "week": "0989529",
                "years": "AZN",
                "sedol": "GB0009895292",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.47,
                "bullAdvice": "2021-12-23 SELL",
                "sector": "Pharmaceutica"
            },
            {
                "navMid": 0.07,
                "navPerShare": null,
                "rsi": 57,
                "midPrice": null,
                "dividend": 2.17,
                "tickerSymbol": "CCH",
                "stockName": "COCACOLA HBC ",
                "profit": 369,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 20.85,
                "techSum": 1,
                "percentUp": 1.27,
                "weekPercentUp": null,
                "marketCapitalisation": 9286,
                "day": "9825130",
                "week": "9825130",
                "years": "CCH",
                "sedol": "CH0198251305",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.15,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Beverages"
            },
            {
                "navMid": 0.11,
                "navPerShare": null,
                "rsi": 52.17,
                "midPrice": null,
                "dividend": 13.72,
                "tickerSymbol": "EVR",
                "stockName": "EVRAZ",
                "profit": 661,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 7.69,
                "techSum": 1,
                "percentUp": 1.25,
                "weekPercentUp": null,
                "marketCapitalisation": 8837,
                "day": "B71N6K8",
                "week": "B71N6K8",
                "years": "EVR",
                "sedol": "GB00B71N6K86",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.07,
                "bullAdvice": "2021-12-14 BUY",
                "sector": "Industrial Me"
            },
            {
                "navMid": 0.26,
                "navPerShare": null,
                "rsi": 64.1,
                "midPrice": null,
                "dividend": 3.18,
                "tickerSymbol": "TSCO",
                "stockName": "TESCO",
                "profit": 717,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 3.37,
                "techSum": 1,
                "percentUp": 1.24,
                "weekPercentUp": null,
                "marketCapitalisation": 22080,
                "day": "BLGZ986",
                "week": "BLGZ986",
                "years": "TSCO",
                "sedol": "GB00BLGZ9862",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.17,
                "bullAdvice": "2021-12-22 SELL",
                "sector": "Personal Care"
            },
            {
                "navMid": 1.04,
                "navPerShare": null,
                "rsi": 50.33,
                "midPrice": null,
                "dividend": 4.6,
                "tickerSymbol": "BP.",
                "stockName": "BP",
                "profit": 3155,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 13.99,
                "techSum": 1,
                "percentUp": 1.2,
                "weekPercentUp": null,
                "marketCapitalisation": 66622,
                "day": "0798059",
                "week": "0798059",
                "years": "BP.",
                "sedol": "GB0007980591",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.3,
                "bullAdvice": "2021-12-13 SELL",
                "sector": "Oil, Gas and "
            },
            {
                "navMid": -0.87,
                "navPerShare": null,
                "rsi": 59.3,
                "midPrice": null,
                "dividend": 8.63,
                "tickerSymbol": "IMB",
                "stockName": "IMP.BRANDS",
                "profit": 2834,
                "cash": null,
                "exDividend": "2022-02-17",
                "netNet": 0,
                "peRatio": 5.39,
                "techSum": 1,
                "percentUp": 1.14,
                "weekPercentUp": null,
                "marketCapitalisation": 15256,
                "day": "0454492",
                "week": "0454492",
                "years": "IMB",
                "sedol": "GB0004544929",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.37,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Tobacco"
            },
            {
                "navMid": 0.04,
                "navPerShare": null,
                "rsi": 57,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SKG",
                "stockName": "SMURFIT KAP.",
                "profit": 484,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": 2,
                "percentUp": 1.14,
                "weekPercentUp": null,
                "marketCapitalisation": 10377,
                "day": "B1RR840",
                "week": "B1RR840",
                "years": "SKG",
                "sedol": "IE00B1RR8406",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.55,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "General Indus"
            },
            {
                "navMid": 1.93,
                "navPerShare": null,
                "rsi": 58.62,
                "midPrice": null,
                "dividend": 3.55,
                "tickerSymbol": "HSBA",
                "stockName": "HSBC HLDGS.UK",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.01,
                "peRatio": 10.74,
                "techSum": 1,
                "percentUp": 1.13,
                "weekPercentUp": null,
                "marketCapitalisation": 90933,
                "day": "0540528",
                "week": "0540528",
                "years": "HSBA",
                "sedol": "GB0005405286",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.23,
                "bullAdvice": "2021-12-01 BUY",
                "sector": "Banks"
            },
            {
                "navMid": 0.15,
                "navPerShare": null,
                "rsi": 64,
                "midPrice": null,
                "dividend": 3.44,
                "tickerSymbol": "SVT",
                "stockName": "SEVERN TRENT",
                "profit": 212,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": 1,
                "percentUp": 1.11,
                "weekPercentUp": null,
                "marketCapitalisation": 7393,
                "day": "B1FH8J7",
                "week": "B1FH8J7",
                "years": "SVT",
                "sedol": "GB00B1FH8J72",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.1,
                "bullAdvice": "2021-12-16 SELL",
                "sector": "Gas, Water an"
            },
            {
                "navMid": -0.04,
                "navPerShare": null,
                "rsi": 64.1,
                "midPrice": null,
                "dividend": 1.81,
                "tickerSymbol": "DGE",
                "stockName": "DIAGEO",
                "profit": 2660,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 35.4,
                "techSum": 1,
                "percentUp": 1.09,
                "weekPercentUp": null,
                "marketCapitalisation": 93456,
                "day": "0237400",
                "week": "0237400",
                "years": "DGE",
                "sedol": "GB0002374006",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.65,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Beverages"
            },
            {
                "navMid": 0.32,
                "navPerShare": null,
                "rsi": 74.5,
                "midPrice": null,
                "dividend": 4.56,
                "tickerSymbol": "NG.",
                "stockName": "NATIONAL GRID",
                "profit": 1255,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 25.48,
                "techSum": 1,
                "percentUp": 1.08,
                "weekPercentUp": null,
                "marketCapitalisation": 39137,
                "day": "BDR05C0",
                "week": "BDR05C0",
                "years": "NG.",
                "sedol": "GB00BDR05C01",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.23,
                "bullAdvice": "2021-11-12 BUY",
                "sector": "Gas, Water an"
            },
            {
                "navMid": -0.1,
                "navPerShare": null,
                "rsi": 50.8,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "MGGT",
                "stockName": "MEGGITT",
                "profit": -314,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 98.59,
                "techSum": 1,
                "percentUp": 0.69,
                "weekPercentUp": null,
                "marketCapitalisation": 5779,
                "day": "0575809",
                "week": "0575809",
                "years": "MGGT",
                "sedol": "GB0005758098",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.14,
                "bullAdvice": "2021-12-14 BUY",
                "sector": "Aerospace and"
            },
            {
                "navMid": 0.04,
                "navPerShare": null,
                "rsi": 52,
                "midPrice": null,
                "dividend": 0.95,
                "tickerSymbol": "CRDA",
                "stockName": "CRODA INTL.",
                "profit": 202,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 55.37,
                "techSum": 0,
                "percentUp": 0.32,
                "weekPercentUp": null,
                "marketCapitalisation": 13966,
                "day": "BJFFLV0",
                "week": "BJFFLV0",
                "years": "CRDA",
                "sedol": "GB00BJFFLV09",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.64,
                "bullAdvice": "2021-12-14 SELL",
                "sector": "Chemicals"
            },
            {
                "navMid": 0.31,
                "navPerShare": null,
                "rsi": 50.6,
                "midPrice": null,
                "dividend": 3.28,
                "tickerSymbol": "PSON",
                "stockName": "PEARSON",
                "profit": 310,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 16.27,
                "techSum": 0,
                "percentUp": 0.25,
                "weekPercentUp": null,
                "marketCapitalisation": 4569,
                "day": "0677608",
                "week": "0677608",
                "years": "PSON",
                "sedol": "GB0006776081",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1,
                "bullAdvice": "2021-12-09 BUY",
                "sector": "Media"
            },
            {
                "navMid": 0.05,
                "navPerShare": null,
                "rsi": 46,
                "midPrice": null,
                "dividend": 0.78,
                "tickerSymbol": "AHT",
                "stockName": "ASHTEAD GRP.",
                "profit": 697,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 32.75,
                "techSum": -1,
                "percentUp": 0.24,
                "weekPercentUp": null,
                "marketCapitalisation": 26804,
                "day": "0053673",
                "week": "0053673",
                "years": "AHT",
                "sedol": "GB0000536739",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.09,
                "bullAdvice": "2021-12-23 BUY",
                "sector": "Industrial Tr"
            },
            {
                "navMid": 0.43,
                "navPerShare": null,
                "rsi": 59.9,
                "midPrice": null,
                "dividend": 9.98,
                "tickerSymbol": "BHP",
                "stockName": "BHP GROUP",
                "profit": 8402,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 13.04,
                "techSum": 1,
                "percentUp": 0.21,
                "weekPercentUp": null,
                "marketCapitalisation": 110212,
                "day": "BH0P3Z9",
                "week": "BH0P3Z9",
                "years": "BHP",
                "sedol": "GB00BH0P3Z91",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.77,
                "bullAdvice": "2021-12-14 BUY",
                "sector": "Industrial Me"
            },
            {
                "navMid": -0.37,
                "navPerShare": null,
                "rsi": 63.7,
                "midPrice": null,
                "dividend": 4.96,
                "tickerSymbol": "GSK",
                "stockName": "GLAXOSMITHKLI",
                "profit": 5749,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 18.91,
                "techSum": 1,
                "percentUp": 0.1,
                "weekPercentUp": null,
                "marketCapitalisation": 81213,
                "day": "0925288",
                "week": "0925288",
                "years": "GSK",
                "sedol": "GB0009252882",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Pharmaceutica"
            },
            {
                "navMid": 0.03,
                "navPerShare": null,
                "rsi": 54.2,
                "midPrice": null,
                "dividend": 3.35,
                "tickerSymbol": "SMDS",
                "stockName": "SMITH(DS)",
                "profit": 182,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 20.84,
                "techSum": 1,
                "percentUp": 0,
                "weekPercentUp": null,
                "marketCapitalisation": 5292,
                "day": "0822011",
                "week": "0822011",
                "years": "SMDS",
                "sedol": "GB0008220112",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.26,
                "bullAdvice": "2021-12-23 BUY",
                "sector": "General Indus"
            },
            {
                "navMid": 0.61,
                "navPerShare": null,
                "rsi": 56.5,
                "midPrice": null,
                "dividend": 10.12,
                "tickerSymbol": "RIO",
                "stockName": "RIO TINTO",
                "profit": 7618,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 5.64,
                "techSum": 1,
                "percentUp": -0.11,
                "weekPercentUp": null,
                "marketCapitalisation": 78805,
                "day": "0718875",
                "week": "0718875",
                "years": "RIO",
                "sedol": "GB0007188757",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.19,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Industrial Me"
            },
            {
                "navMid": 0.06,
                "navPerShare": null,
                "rsi": 59,
                "midPrice": null,
                "dividend": 2.7,
                "tickerSymbol": "DCC",
                "stockName": "DCC",
                "profit": 293,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 20.07,
                "techSum": 1,
                "percentUp": -0.11,
                "weekPercentUp": null,
                "marketCapitalisation": 5988,
                "day": "0242493",
                "week": "0242493",
                "years": "DCC",
                "sedol": "IE0002424939",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.25,
                "bullAdvice": "2021-12-02 BUY",
                "sector": "Industrial Su"
            },
            {
                "navMid": 0.04,
                "navPerShare": null,
                "rsi": 40.8,
                "midPrice": null,
                "dividend": 0.91,
                "tickerSymbol": "PRU",
                "stockName": "PRUDENTIAL",
                "profit": 403,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 0,
                "techSum": -1,
                "percentUp": -0.27,
                "weekPercentUp": null,
                "marketCapitalisation": 35017,
                "day": "0709954",
                "week": "0709954",
                "years": "PRU",
                "sedol": "GB0007099541",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.32,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Life Insuranc"
            },
            {
                "navMid": -0.87,
                "navPerShare": null,
                "rsi": 59.8,
                "midPrice": null,
                "dividend": 7.84,
                "tickerSymbol": "BATS",
                "stockName": "BR.AMER.TOB.",
                "profit": 6400,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 10.2,
                "techSum": 1,
                "percentUp": -0.41,
                "weekPercentUp": null,
                "marketCapitalisation": 63103,
                "day": "0287580",
                "week": "0287580",
                "years": "BATS",
                "sedol": "GB0002875804",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.4,
                "bullAdvice": "2021-12-23 SELL",
                "sector": "Tobacco"
            },
            {
                "navMid": 0.38,
                "navPerShare": null,
                "rsi": 0,
                "midPrice": null,
                "dividend": 3.96,
                "tickerSymbol": "UU.",
                "stockName": "UTD. UTILITIE",
                "profit": 107,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 100.02,
                "techSum": 0,
                "percentUp": -0.45,
                "weekPercentUp": null,
                "marketCapitalisation": 7453,
                "day": "B39J2M4",
                "week": "B39J2M4",
                "years": "UU.",
                "sedol": "GB00B39J2M42",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.31,
                "bullAdvice": "2021-12-14 SELL",
                "sector": "Gas, Water an"
            },
            {
                "navMid": 0.1,
                "navPerShare": null,
                "rsi": 59,
                "midPrice": null,
                "dividend": 4.89,
                "tickerSymbol": "ADM",
                "stockName": "ADMIRAL GRP",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 8.41,
                "techSum": 0,
                "percentUp": -0.48,
                "weekPercentUp": null,
                "marketCapitalisation": 9271,
                "day": "B02J639",
                "week": "B02J639",
                "years": "ADM",
                "sedol": "GB00B02J6398",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.58,
                "bullAdvice": "2021-12-07 BUY",
                "sector": "Non-life Insu"
            },
            {
                "navMid": 0.32,
                "navPerShare": null,
                "rsi": 42.8,
                "midPrice": null,
                "dividend": 7.5,
                "tickerSymbol": "POLY",
                "stockName": "POLYMETAL INT",
                "profit": 847,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 7.36,
                "techSum": -1,
                "percentUp": -0.53,
                "weekPercentUp": null,
                "marketCapitalisation": 6119,
                "day": "B6T5S47",
                "week": "B6T5S47",
                "years": "POLY",
                "sedol": "JE00B6T5S470",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.31,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Precious Meta"
            },
            {
                "navMid": 0.35,
                "navPerShare": null,
                "rsi": 51.7,
                "midPrice": null,
                "dividend": 2.92,
                "tickerSymbol": "MNDI",
                "stockName": "MONDI",
                "profit": 517,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 17.77,
                "techSum": 1,
                "percentUp": -0.66,
                "weekPercentUp": null,
                "marketCapitalisation": 8806,
                "day": "B1CRLC4",
                "week": "B1CRLC4",
                "years": "MNDI",
                "sedol": "GB00B1CRLC47",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.52,
                "bullAdvice": "2021-12-09 SELL",
                "sector": "Industrial Ma"
            },
            {
                "navMid": -0.17,
                "navPerShare": null,
                "rsi": 51.59,
                "midPrice": null,
                "dividend": 3.73,
                "tickerSymbol": "ULVR",
                "stockName": "UNILEVER",
                "profit": 4961,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 22.61,
                "techSum": 0,
                "percentUp": -0.71,
                "weekPercentUp": null,
                "marketCapitalisation": 101432,
                "day": "B10RZP7",
                "week": "B10RZP7",
                "years": "ULVR",
                "sedol": "GB00B10RZP78",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.08,
                "bullAdvice": "2021-12-22 SELL",
                "sector": "Personal Care"
            },
            {
                "navMid": 0.27,
                "navPerShare": null,
                "rsi": 49.9,
                "midPrice": null,
                "dividend": 6.69,
                "tickerSymbol": "VOD",
                "stockName": "VODAFONE GRP.",
                "profit": 100,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": -1,
                "percentUp": -0.87,
                "weekPercentUp": null,
                "marketCapitalisation": 30612,
                "day": "BH4HKS3",
                "week": "BH4HKS3",
                "years": "VOD",
                "sedol": "GB00BH4HKS39",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Telecommunica"
            },
            {
                "navMid": 0.25,
                "navPerShare": null,
                "rsi": 40,
                "midPrice": null,
                "dividend": 1.72,
                "tickerSymbol": "HIK",
                "stockName": "HIKMA",
                "profit": 336,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 14.54,
                "techSum": -1,
                "percentUp": -1.07,
                "weekPercentUp": null,
                "marketCapitalisation": 5067,
                "day": "B0LCW08",
                "week": "B0LCW08",
                "years": "HIK",
                "sedol": "GB00B0LCW083",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.69,
                "bullAdvice": "2021-12-14 BUY",
                "sector": "Pharmaceutica"
            },
            {
                "navMid": 0.34,
                "navPerShare": null,
                "rsi": 40,
                "midPrice": null,
                "dividend": 2.92,
                "tickerSymbol": "PNN",
                "stockName": "PENNON GROUP",
                "profit": 108,
                "cash": null,
                "exDividend": "2022-01-27",
                "netNet": 0,
                "peRatio": 0,
                "techSum": -1,
                "percentUp": -1.09,
                "weekPercentUp": null,
                "marketCapitalisation": 3170,
                "day": "BNNTLN4",
                "week": "BNNTLN4",
                "years": "PNN",
                "sedol": "GB00BNNTLN49",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.51,
                "bullAdvice": "2021-12-09 BUY",
                "sector": "Gas, Water an"
            },
            {
                "navMid": -0.06,
                "navPerShare": null,
                "rsi": 37.3,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "JET",
                "stockName": "JUST EAT TAKE",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": -1,
                "percentUp": -1.11,
                "weekPercentUp": null,
                "marketCapitalisation": 8604,
                "day": "1201570",
                "week": "1201570",
                "years": "JET",
                "sedol": "NL0012015705",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Software and "
            },
            {
                "navMid": 0.48,
                "navPerShare": null,
                "rsi": 50.18,
                "midPrice": null,
                "dividend": 2.64,
                "tickerSymbol": "FRES",
                "stockName": "FRESNILLO",
                "profit": 292,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 14.44,
                "techSum": 1,
                "percentUp": -1.53,
                "weekPercentUp": null,
                "marketCapitalisation": 6580,
                "day": "B2QPKJ1",
                "week": "B2QPKJ1",
                "years": "FRES",
                "sedol": "GB00B2QPKJ12",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.06,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Precious Meta"
            },
            {
                "navMid": 0.13,
                "navPerShare": null,
                "rsi": 46.5,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "OCDO",
                "stockName": "OCADO",
                "profit": -126,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 0,
                "techSum": -1,
                "percentUp": -3.04,
                "weekPercentUp": null,
                "marketCapitalisation": 12460,
                "day": "B3MBS74",
                "week": "B3MBS74",
                "years": "OCDO",
                "sedol": "GB00B3MBS747",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 2.01,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Personal Care"
            },
            {
                "navMid": 0.56,
                "navPerShare": null,
                "rsi": 43,
                "midPrice": null,
                "dividend": 3.94,
                "tickerSymbol": "ANTO",
                "stockName": "ANTOFAGASTA",
                "profit": 389,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 16.76,
                "techSum": -1,
                "percentUp": -3.17,
                "weekPercentUp": null,
                "marketCapitalisation": 13013,
                "day": "0045614",
                "week": "0045614",
                "years": "ANTO",
                "sedol": "GB0000456144",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.49,
                "bullAdvice": "2021-12-23 BUY",
                "sector": "Industrial Me"
            }
        ]

    )

)
    //  return next();
});


module.exports = router;