'use strict';
var express = require('express');
var router = express.Router();
var app = express();
var path = require('path');
//var pthv = require('./pthv');

/* GET home page. */

router.get('/', (req, res) => {
    console.log("in here a");

    console.log(req.path);
    console.log(req.params);
    console.log(req.params.useridname);
    // app.use('/pthv/:useridname', pthv);
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify(
        [
            {
                "navMid": 1.06,
                "navPerShare": null,
                "rsi": 66.35,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "IAG",
                "stockName": "INTL CONSOL A",
                "profit": -6154,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -0.92,
                "techSum": 1,
                "percentUp": 13.29,
                "weekPercentUp": null,
                "marketCapitalisation": 8017,
                "day": "7754201",
                "week": "7754201",
                "years": "IAG",
                "sedol": "ES0177542018",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.62,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 0.46,
                "navPerShare": null,
                "rsi": 69.1,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "EZJ",
                "stockName": "EASYJET",
                "profit": -858,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -3.93,
                "techSum": 1,
                "percentUp": 12.19,
                "weekPercentUp": null,
                "marketCapitalisation": 4731,
                "day": "B7KR2P8",
                "week": "B7KR2P8",
                "years": "EZJ",
                "sedol": "GB00B7KR2P84",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.57,
                "bullAdvice": "2022-01-05 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 1,
                "navPerShare": null,
                "rsi": 0,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "LLOY",
                "stockName": "LLOYDS GRP.",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 43.33,
                "techSum": 2,
                "percentUp": 8.34,
                "weekPercentUp": null,
                "marketCapitalisation": 36932,
                "day": "0870612",
                "week": "0870612",
                "years": "LLOY",
                "sedol": "GB0008706128",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.93,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Banks"
            },
            {
                "navMid": 1.26,
                "navPerShare": null,
                "rsi": 72.8,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "NWG",
                "stockName": "ROYAL BANK SC",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.01,
                "peRatio": -39.21,
                "techSum": 2,
                "percentUp": 7.53,
                "weekPercentUp": null,
                "marketCapitalisation": 27489,
                "day": "B7T7721",
                "week": "B7T7721",
                "years": "NWG",
                "sedol": "GB00B7T77214",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 2.06,
                "bullAdvice": null,
                "sector": "Banks"
            },
            {
                "navMid": 2.97,
                "navPerShare": null,
                "rsi": 69.4,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "STAN",
                "stockName": "STAND.CHART.",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.01,
                "peRatio": 62.55,
                "techSum": 2,
                "percentUp": 6.72,
                "weekPercentUp": null,
                "marketCapitalisation": 14697,
                "day": "0408284",
                "week": "0408284",
                "years": "STAN",
                "sedol": "GB0004082847",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 3.36,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Banks"
            },
            {
                "navMid": 1,
                "navPerShare": null,
                "rsi": 61.14,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BP.",
                "stockName": "BP",
                "profit": 3155,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -4.82,
                "techSum": 1,
                "percentUp": 6.47,
                "weekPercentUp": null,
                "marketCapitalisation": 70005,
                "day": "0798059",
                "week": "0798059",
                "years": "BP.",
                "sedol": "GB0007980591",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Oil, Gas and "
            },
            {
                "navMid": -0.27,
                "navPerShare": null,
                "rsi": 64,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "MRO",
                "stockName": "MELROSE IND",
                "profit": -526,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -13.63,
                "techSum": 1,
                "percentUp": 6.37,
                "weekPercentUp": null,
                "marketCapitalisation": 7284,
                "day": "BNR5MZ7",
                "week": "BNR5MZ7",
                "years": "MRO",
                "sedol": "GB00BNR5MZ78",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.19,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "General Indus"
            },
            {
                "navMid": 1.81,
                "navPerShare": null,
                "rsi": 73.59,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "HSBA",
                "stockName": "HSBC HLDGS.UK",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.01,
                "peRatio": 34.29,
                "techSum": 2,
                "percentUp": 6.23,
                "weekPercentUp": null,
                "marketCapitalisation": 97094,
                "day": "0540528",
                "week": "0540528",
                "years": "HSBA",
                "sedol": "GB0005405286",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.89,
                "bullAdvice": "2021-12-01 BUY",
                "sector": "Banks"
            },
            {
                "navMid": 1.21,
                "navPerShare": null,
                "rsi": 62.4,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RDSB",
                "stockName": "RDS 'B'",
                "profit": -16906,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -8.43,
                "techSum": 1,
                "percentUp": 6.21,
                "weekPercentUp": null,
                "marketCapitalisation": 132269,
                "day": "B03MM40",
                "week": "B03MM40",
                "years": "RDSB",
                "sedol": "GB00B03MM408",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.34,
                "bullAdvice": "2022-01-05 BUY",
                "sector": "Oil, Gas and "
            },
            {
                "navMid": 1.21,
                "navPerShare": null,
                "rsi": 61.9,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RDSA",
                "stockName": "RDS 'A'",
                "profit": -16906,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -8.42,
                "techSum": 2,
                "percentUp": 6.18,
                "weekPercentUp": null,
                "marketCapitalisation": 132007,
                "day": "B03MLX2",
                "week": "B03MLX2",
                "years": "RDSA",
                "sedol": "GB00B03MLX29",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.34,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Oil, Gas and "
            },
            {
                "navMid": 1.67,
                "navPerShare": null,
                "rsi": 67.97,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BARC",
                "stockName": "BARCLAYS",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.01,
                "peRatio": 22.78,
                "techSum": 2,
                "percentUp": 5.83,
                "weekPercentUp": null,
                "marketCapitalisation": 33580,
                "day": "3134865",
                "week": "3134865",
                "years": "BARC",
                "sedol": "GB0031348658",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Banks"
            },
            {
                "navMid": 0,
                "navPerShare": null,
                "rsi": 66,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "IHG",
                "stockName": "INTERCON. HOT",
                "profit": -203,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -47.96,
                "techSum": 1,
                "percentUp": 5.49,
                "weekPercentUp": null,
                "marketCapitalisation": 9260,
                "day": "BHJYC05",
                "week": "BHJYC05",
                "years": "IHG",
                "sedol": "GB00BHJYC057",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.97,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 0.85,
                "navPerShare": null,
                "rsi": 65,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "WTB",
                "stockName": "WHITBREAD",
                "profit": -907,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -6.54,
                "techSum": 1,
                "percentUp": 4.88,
                "weekPercentUp": null,
                "marketCapitalisation": 6401,
                "day": "B1KJJ40",
                "week": "B1KJJ40",
                "years": "WTB",
                "sedol": "GB00B1KJJ408",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.1,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 0.51,
                "navPerShare": null,
                "rsi": 67.4,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "AAL",
                "stockName": "ANGLO AMERICA",
                "profit": 1629,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 25.51,
                "techSum": 1,
                "percentUp": 4.38,
                "weekPercentUp": null,
                "marketCapitalisation": 42497,
                "day": "B1XZS82",
                "week": "B1XZS82",
                "years": "AAL",
                "sedol": "GB00B1XZS820",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.44,
                "bullAdvice": null,
                "sector": "Industrial Me"
            },
            {
                "navMid": -0.62,
                "navPerShare": null,
                "rsi": 63,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "INF",
                "stockName": "INFORMA",
                "profit": -1042,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -7.37,
                "techSum": 1,
                "percentUp": 4.35,
                "weekPercentUp": null,
                "marketCapitalisation": 8132,
                "day": "BMJ6DW5",
                "week": "BMJ6DW5",
                "years": "INF",
                "sedol": "GB00BMJ6DW54",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.46,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Media"
            },
            {
                "navMid": 0.06,
                "navPerShare": null,
                "rsi": 60.85,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BT.A",
                "stockName": "BT GROUP",
                "profit": 1472,
                "cash": null,
                "exDividend": "2021-12-30",
                "netNet": 0,
                "peRatio": 11.86,
                "techSum": 2,
                "percentUp": 4.17,
                "weekPercentUp": null,
                "marketCapitalisation": 17414,
                "day": "3091357",
                "week": "3091357",
                "years": "BT.A",
                "sedol": "GB0030913577",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Telecommunica"
            },
            {
                "navMid": -0.16,
                "navPerShare": null,
                "rsi": 59.01,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ITV",
                "stockName": "ITV",
                "profit": 285,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 16.18,
                "techSum": 1,
                "percentUp": 3.61,
                "weekPercentUp": null,
                "marketCapitalisation": 4629,
                "day": "3398649",
                "week": "3398649",
                "years": "ITV",
                "sedol": "GB0033986497",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.44,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Media"
            },
            {
                "navMid": -0.05,
                "navPerShare": null,
                "rsi": 66.6,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "CPG",
                "stockName": "COMPASS GROUP",
                "profit": 357,
                "cash": null,
                "exDividend": "2022-01-20",
                "netNet": 0,
                "peRatio": 84.7,
                "techSum": 1,
                "percentUp": 3.55,
                "weekPercentUp": null,
                "marketCapitalisation": 30224,
                "day": "BD6K457",
                "week": "BD6K457",
                "years": "CPG",
                "sedol": "GB00BD6K4575",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.53,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Consumer Serv"
            },
            {
                "navMid": -0.24,
                "navPerShare": null,
                "rsi": 71.2,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "WPP",
                "stockName": "WPP",
                "profit": -2974,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -4.81,
                "techSum": 1,
                "percentUp": 3.46,
                "weekPercentUp": null,
                "marketCapitalisation": 13438,
                "day": "B8KF9B4",
                "week": "B8KF9B4",
                "years": "WPP",
                "sedol": "JE00B8KF9B49",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.03,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Media"
            },
            {
                "navMid": 0.59,
                "navPerShare": null,
                "rsi": 66.2,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RIO",
                "stockName": "RIO TINTO",
                "profit": 7618,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 11.43,
                "techSum": 1,
                "percentUp": 3.31,
                "weekPercentUp": null,
                "marketCapitalisation": 82231,
                "day": "0718875",
                "week": "0718875",
                "years": "RIO",
                "sedol": "GB0007188757",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.86,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Industrial Me"
            },
            {
                "navMid": 0.74,
                "navPerShare": null,
                "rsi": 67.8,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "AV.",
                "stockName": "AVIVA",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 6.07,
                "techSum": 1,
                "percentUp": 3.15,
                "weekPercentUp": null,
                "marketCapitalisation": 16038,
                "day": "0216238",
                "week": "0216238",
                "years": "AV.",
                "sedol": "GB0002162385",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-14 BUY",
                "sector": "Life Insuranc"
            },
            {
                "navMid": 0,
                "navPerShare": null,
                "rsi": 62,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "MNG",
                "stockName": "M&G PLC",
                "profit": -55,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 4.65,
                "techSum": 1,
                "percentUp": 2.99,
                "weekPercentUp": null,
                "marketCapitalisation": 5370,
                "day": "BKFB1C6",
                "week": "BKFB1C6",
                "years": "MNG",
                "sedol": "GB00BKFB1C65",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Investment Ba"
            },
            {
                "navMid": 0.65,
                "navPerShare": null,
                "rsi": 61.09,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "GLEN",
                "stockName": "GLENCORE",
                "profit": -1484,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -37.86,
                "techSum": 1,
                "percentUp": 2.92,
                "weekPercentUp": null,
                "marketCapitalisation": 51230,
                "day": "B4T3BW6",
                "week": "B4T3BW6",
                "years": "GLEN",
                "sedol": "JE00B4T3BW64",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.9,
                "bullAdvice": "2022-01-05 BUY",
                "sector": "Industrial Me"
            },
            {
                "navMid": -0.85,
                "navPerShare": null,
                "rsi": 65.9,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BATS",
                "stockName": "BR.AMER.TOB.",
                "profit": 6400,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 10.03,
                "techSum": 2,
                "percentUp": 2.84,
                "weekPercentUp": null,
                "marketCapitalisation": 64469,
                "day": "0287580",
                "week": "0287580",
                "years": "BATS",
                "sedol": "GB0002875804",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.34,
                "bullAdvice": "2021-12-23 SELL",
                "sector": "Tobacco"
            },
            {
                "navMid": 0,
                "navPerShare": null,
                "rsi": 53.66,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RR.",
                "stockName": "ROLLS-ROYCE H",
                "profit": -1315,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -2.38,
                "techSum": 1,
                "percentUp": 2.44,
                "weekPercentUp": null,
                "marketCapitalisation": 10567,
                "day": "B63H849",
                "week": "B63H849",
                "years": "RR.",
                "sedol": "GB00B63H8491",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.38,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Aerospace and"
            },
            {
                "navMid": 0.48,
                "navPerShare": null,
                "rsi": 62,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ABF",
                "stockName": "A.B.FOOD",
                "profit": 478,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 33.92,
                "techSum": 1,
                "percentUp": 2.38,
                "weekPercentUp": null,
                "marketCapitalisation": 16261,
                "day": "0673123",
                "week": "0673123",
                "years": "ABF",
                "sedol": "GB0006731235",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.09,
                "bullAdvice": null,
                "sector": "Food Producer"
            },
            {
                "navMid": 1.18,
                "navPerShare": null,
                "rsi": 57.2,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "CCL",
                "stockName": "CARNIVAL",
                "profit": -6902,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -1.47,
                "techSum": 1,
                "percentUp": 2.36,
                "weekPercentUp": null,
                "marketCapitalisation": 16940,
                "day": "3121522",
                "week": "3121522",
                "years": "CCL",
                "sedol": "GB0031215220",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.13,
                "bullAdvice": "2022-01-05 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 0.04,
                "navPerShare": null,
                "rsi": 64,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SKG",
                "stockName": "SMURFIT KAP.",
                "profit": 484,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 20.13,
                "techSum": 1,
                "percentUp": 2.16,
                "weekPercentUp": null,
                "marketCapitalisation": 10768,
                "day": "B1RR840",
                "week": "B1RR840",
                "years": "SKG",
                "sedol": "IE00B1RR8406",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 49.72,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "General Indus"
            },
            {
                "navMid": 0.42,
                "navPerShare": null,
                "rsi": 64,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BHP",
                "stockName": "BHP GROUP",
                "profit": 8402,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 13.9,
                "techSum": 1,
                "percentUp": 1.94,
                "weekPercentUp": null,
                "marketCapitalisation": 113550,
                "day": "BH0P3Z9",
                "week": "BH0P3Z9",
                "years": "BHP",
                "sedol": "GB00BH0P3Z91",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.02,
                "bullAdvice": "2021-12-14 BUY",
                "sector": "Industrial Me"
            },
            {
                "navMid": 0.03,
                "navPerShare": null,
                "rsi": 62.2,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SMDS",
                "stockName": "SMITH(DS)",
                "profit": 182,
                "cash": null,
                "exDividend": "2022-04-07",
                "netNet": 0,
                "peRatio": 28.01,
                "techSum": 1,
                "percentUp": 1.93,
                "weekPercentUp": null,
                "marketCapitalisation": 5465,
                "day": "0822011",
                "week": "0822011",
                "years": "SMDS",
                "sedol": "GB0008220112",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.38,
                "bullAdvice": "2021-12-23 BUY",
                "sector": "General Indus"
            },
            {
                "navMid": 0.26,
                "navPerShare": null,
                "rsi": 53.4,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "VOD",
                "stockName": "VODAFONE GRP.",
                "profit": 100,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 352.32,
                "techSum": 1,
                "percentUp": 1.79,
                "weekPercentUp": null,
                "marketCapitalisation": 30978,
                "day": "BH4HKS3",
                "week": "BH4HKS3",
                "years": "VOD",
                "sedol": "GB00BH4HKS39",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.87,
                "bullAdvice": "2022-01-06 BUY",
                "sector": "Telecommunica"
            },
            {
                "navMid": 0.07,
                "navPerShare": null,
                "rsi": 61.5,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SN.",
                "stockName": "SMITH&NEPHEW",
                "profit": 470,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 34.85,
                "techSum": 1,
                "percentUp": 1.56,
                "weekPercentUp": null,
                "marketCapitalisation": 11538,
                "day": "0922320",
                "week": "0922320",
                "years": "SN.",
                "sedol": "GB0009223206",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.76,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Medical Equip"
            },
            {
                "navMid": 1.09,
                "navPerShare": null,
                "rsi": 52.8,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SBRY",
                "stockName": "SAINSBURY(J)",
                "profit": -287,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -21.55,
                "techSum": 1,
                "percentUp": 1.45,
                "weekPercentUp": null,
                "marketCapitalisation": 6534,
                "day": "B019KW7",
                "week": "B019KW7",
                "years": "SBRY",
                "sedol": "GB00B019KW72",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.17,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Personal Care"
            },
            {
                "navMid": -0.66,
                "navPerShare": null,
                "rsi": 70.41,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "CNA",
                "stockName": "CENTRICA",
                "profit": -274,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 103.89,
                "techSum": 1,
                "percentUp": 1.39,
                "weekPercentUp": null,
                "marketCapitalisation": 4277,
                "day": "B033F22",
                "week": "B033F22",
                "years": "CNA",
                "sedol": "GB00B033F229",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.37,
                "bullAdvice": "2022-01-06 SELL",
                "sector": "Gas, Water an"
            },
            {
                "navMid": 0.05,
                "navPerShare": null,
                "rsi": 51,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "AHT",
                "stockName": "ASHTEAD GRP.",
                "profit": 697,
                "cash": null,
                "exDividend": "2022-01-13",
                "netNet": 0,
                "peRatio": 39.18,
                "techSum": 1,
                "percentUp": 1.32,
                "weekPercentUp": null,
                "marketCapitalisation": 27259,
                "day": "0053673",
                "week": "0053673",
                "years": "AHT",
                "sedol": "GB0000536739",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.16,
                "bullAdvice": "2021-12-23 BUY",
                "sector": "Industrial Tr"
            },
            {
                "navMid": 0.34,
                "navPerShare": null,
                "rsi": 57.3,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "MNDI",
                "stockName": "MONDI",
                "profit": 517,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 17.13,
                "techSum": 1,
                "percentUp": 1.21,
                "weekPercentUp": null,
                "marketCapitalisation": 9005,
                "day": "B1CRLC4",
                "week": "B1CRLC4",
                "years": "MNDI",
                "sedol": "GB00B1CRLC47",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.86,
                "bullAdvice": "2021-12-29 BUY",
                "sector": "Industrial Ma"
            },
            {
                "navMid": 0.28,
                "navPerShare": null,
                "rsi": 56.95,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "PHNX",
                "stockName": "PHOENIX GRP H",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 7.19,
                "techSum": 1,
                "percentUp": 1.08,
                "weekPercentUp": null,
                "marketCapitalisation": 6587,
                "day": "BGXQNP2",
                "week": "BGXQNP2",
                "years": "PHNX",
                "sedol": "GB00BGXQNP29",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.45,
                "bullAdvice": null,
                "sector": "Life Insuranc"
            },
            {
                "navMid": 0.07,
                "navPerShare": null,
                "rsi": 61,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "CCH",
                "stockName": "COCACOLA HBC ",
                "profit": 369,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 25.44,
                "techSum": 1,
                "percentUp": 0.9,
                "weekPercentUp": null,
                "marketCapitalisation": 9575,
                "day": "9825130",
                "week": "9825130",
                "years": "CCH",
                "sedol": "CH0198251305",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.19,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Beverages"
            },
            {
                "navMid": -0.85,
                "navPerShare": null,
                "rsi": 62.8,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "IMB",
                "stockName": "IMP.BRANDS",
                "profit": 2834,
                "cash": null,
                "exDividend": "2022-02-17",
                "netNet": 0,
                "peRatio": 5.46,
                "techSum": 1,
                "percentUp": 0.87,
                "weekPercentUp": null,
                "marketCapitalisation": 15507,
                "day": "0454492",
                "week": "0454492",
                "years": "IMB",
                "sedol": "GB0004544929",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.54,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Tobacco"
            },
            {
                "navMid": 0.52,
                "navPerShare": null,
                "rsi": 0,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "LGEN",
                "stockName": "LEGAL&GEN.",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 11.11,
                "techSum": 0,
                "percentUp": 0.85,
                "weekPercentUp": null,
                "marketCapitalisation": 17911,
                "day": "0560399",
                "week": "0560399",
                "years": "LGEN",
                "sedol": "GB0005603997",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Life Insuranc"
            },
            {
                "navMid": -0.1,
                "navPerShare": null,
                "rsi": 62.3,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "MGGT",
                "stockName": "MEGGITT",
                "profit": -314,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -18.44,
                "techSum": 1,
                "percentUp": 0.82,
                "weekPercentUp": null,
                "marketCapitalisation": 5826,
                "day": "0575809",
                "week": "0575809",
                "years": "MGGT",
                "sedol": "GB0005758098",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.27,
                "bullAdvice": "2021-12-29 BUY",
                "sector": "Aerospace and"
            },
            {
                "navMid": 0.04,
                "navPerShare": null,
                "rsi": 45,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "PRU",
                "stockName": "PRUDENTIAL",
                "profit": 403,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 21.45,
                "techSum": -1,
                "percentUp": 0.51,
                "weekPercentUp": null,
                "marketCapitalisation": 35305,
                "day": "0709954",
                "week": "0709954",
                "years": "PRU",
                "sedol": "GB0007099541",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.74,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Life Insuranc"
            },
            {
                "navMid": 0.13,
                "navPerShare": null,
                "rsi": 60.4,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SMIN",
                "stockName": "SMITHS GROUP",
                "profit": 156,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 22.29,
                "techSum": 1,
                "percentUp": 0.51,
                "weekPercentUp": null,
                "marketCapitalisation": 6277,
                "day": "B1WY233",
                "week": "B1WY233",
                "years": "SMIN",
                "sedol": "GB00B1WY2338",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.81,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "General Indus"
            },
            {
                "navMid": 0.11,
                "navPerShare": null,
                "rsi": 51.3,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "EVR",
                "stockName": "EVRAZ",
                "profit": 661,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 14.24,
                "techSum": 1,
                "percentUp": 0.42,
                "weekPercentUp": null,
                "marketCapitalisation": 8837,
                "day": "B71N6K8",
                "week": "B71N6K8",
                "years": "EVR",
                "sedol": "GB00B71N6K86",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.4,
                "bullAdvice": "2021-12-14 BUY",
                "sector": "Industrial Me"
            },
            {
                "navMid": 0.14,
                "navPerShare": null,
                "rsi": 51.3,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BRBY",
                "stockName": "BURBERRY GRP",
                "profit": 376,
                "cash": null,
                "exDividend": "2021-12-16",
                "netNet": 0,
                "peRatio": 19.57,
                "techSum": 0,
                "percentUp": 0.42,
                "weekPercentUp": null,
                "marketCapitalisation": 7323,
                "day": "3174300",
                "week": "3174300",
                "years": "BRBY",
                "sedol": "GB0031743007",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.28,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Personal Good"
            },
            {
                "navMid": -0.28,
                "navPerShare": null,
                "rsi": 50.8,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BA.",
                "stockName": "BAE SYSTEMS P",
                "profit": 1476,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 13.51,
                "techSum": 0,
                "percentUp": 0.37,
                "weekPercentUp": null,
                "marketCapitalisation": 17404,
                "day": "0263494",
                "week": "0263494",
                "years": "BA.",
                "sedol": "GB0002634946",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.37,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Aerospace and"
            },
            {
                "navMid": 0.25,
                "navPerShare": null,
                "rsi": 62.17,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "TSCO",
                "stockName": "TESCO",
                "profit": 717,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 4.58,
                "techSum": 1,
                "percentUp": 0.35,
                "weekPercentUp": null,
                "marketCapitalisation": 22411,
                "day": "BLGZ986",
                "week": "BLGZ986",
                "years": "TSCO",
                "sedol": "GB00BLGZ9862",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.36,
                "bullAdvice": "2021-12-30 BUY",
                "sector": "Personal Care"
            },
            {
                "navMid": 0.06,
                "navPerShare": null,
                "rsi": 57.32,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "DCC",
                "stockName": "DCC",
                "profit": 293,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 20.54,
                "techSum": 1,
                "percentUp": 0.27,
                "weekPercentUp": null,
                "marketCapitalisation": 6018,
                "day": "0242493",
                "week": "0242493",
                "years": "DCC",
                "sedol": "IE0002424939",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.26,
                "bullAdvice": "2021-12-02 BUY",
                "sector": "Industrial Su"
            },
            {
                "navMid": 0.28,
                "navPerShare": null,
                "rsi": 59,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "CRH",
                "stockName": "CRH",
                "profit": 875,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 37.47,
                "techSum": 1,
                "percentUp": 0.11,
                "weekPercentUp": null,
                "marketCapitalisation": 30272,
                "day": "0182704",
                "week": "0182704",
                "years": "CRH",
                "sedol": "IE0001827041",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.54,
                "bullAdvice": "2022-01-06 SELL",
                "sector": "Construction "
            },
            {
                "navMid": 0.05,
                "navPerShare": null,
                "rsi": 60.9,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "STJ",
                "stockName": "ST.JAMES'S PL",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 34.43,
                "techSum": 1,
                "percentUp": 0,
                "weekPercentUp": null,
                "marketCapitalisation": 9135,
                "day": "0766937",
                "week": "0766937",
                "years": "STJ",
                "sedol": "GB0007669376",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.55,
                "bullAdvice": "2022-01-06 SELL",
                "sector": "Life Insuranc"
            },
            {
                "navMid": 0.31,
                "navPerShare": null,
                "rsi": 50.9,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "PSON",
                "stockName": "PEARSON",
                "profit": 310,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 14.74,
                "techSum": 0,
                "percentUp": -0.16,
                "weekPercentUp": null,
                "marketCapitalisation": 4583,
                "day": "0677608",
                "week": "0677608",
                "years": "PSON",
                "sedol": "GB0006776081",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.4,
                "bullAdvice": "2021-12-09 BUY",
                "sector": "Media"
            },
            {
                "navMid": 1.54,
                "navPerShare": null,
                "rsi": 60,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "LAND",
                "stockName": "LAND SECS.",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.04,
                "peRatio": -4.09,
                "techSum": 1,
                "percentUp": -0.58,
                "weekPercentUp": null,
                "marketCapitalisation": 5702,
                "day": "BYW0PQ6",
                "week": "BYW0PQ6",
                "years": "LAND",
                "sedol": "GB00BYW0PQ60",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.59,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Real Estate I"
            },
            {
                "navMid": 0.34,
                "navPerShare": null,
                "rsi": 45,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "PNN",
                "stockName": "PENNON GROUP",
                "profit": 108,
                "cash": null,
                "exDividend": "2022-01-27",
                "netNet": 0,
                "peRatio": 1.87,
                "techSum": -1,
                "percentUp": -0.8,
                "weekPercentUp": null,
                "marketCapitalisation": 3176,
                "day": "BNNTLN4",
                "week": "BNNTLN4",
                "years": "PNN",
                "sedol": "GB00BNNTLN49",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.25,
                "bullAdvice": "2021-12-24 BUY",
                "sector": "Gas, Water an"
            },
            {
                "navMid": 0.58,
                "navPerShare": null,
                "rsi": 60.49,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "TW.",
                "stockName": "TAYLOR WIMPEY",
                "profit": 674,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 27.71,
                "techSum": 1,
                "percentUp": -0.85,
                "weekPercentUp": null,
                "marketCapitalisation": 6369,
                "day": "0878230",
                "week": "0878230",
                "years": "TW.",
                "sedol": "GB0008782301",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.43,
                "bullAdvice": "2022-01-06 SELL",
                "sector": "Household Goo"
            },
            {
                "navMid": 0.52,
                "navPerShare": null,
                "rsi": 57,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BKG",
                "stockName": "BERKELEY GP.H",
                "profit": 423,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 14.15,
                "techSum": 1,
                "percentUp": -0.87,
                "weekPercentUp": null,
                "marketCapitalisation": 5381,
                "day": "BLJNXL8",
                "week": "BLJNXL8",
                "years": "BKG",
                "sedol": "GB00BLJNXL82",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.06,
                "bullAdvice": "2021-12-31 SELL",
                "sector": "Household Goo"
            },
            {
                "navMid": -0.02,
                "navPerShare": null,
                "rsi": 55,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ITRK",
                "stockName": "INTERTEK GROU",
                "profit": 247,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 36.63,
                "techSum": 1,
                "percentUp": -1.02,
                "weekPercentUp": null,
                "marketCapitalisation": 9103,
                "day": "3163836",
                "week": "3163836",
                "years": "ITRK",
                "sedol": "GB0031638363",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.01,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Industrial Su"
            },
            {
                "navMid": 0.53,
                "navPerShare": null,
                "rsi": 55.5,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BDEV",
                "stockName": "BARRATT DEVEL",
                "profit": 660,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 11.39,
                "techSum": 1,
                "percentUp": -1.06,
                "weekPercentUp": null,
                "marketCapitalisation": 7561,
                "day": "0081180",
                "week": "0081180",
                "years": "BDEV",
                "sedol": "GB0000811801",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.16,
                "bullAdvice": "2022-01-06 SELL",
                "sector": "Household Goo"
            },
            {
                "navMid": -0.17,
                "navPerShare": null,
                "rsi": 44.9,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ULVR",
                "stockName": "UNILEVER",
                "profit": 4961,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 20.34,
                "techSum": -2,
                "percentUp": -1.46,
                "weekPercentUp": null,
                "marketCapitalisation": 100534,
                "day": "B10RZP7",
                "week": "B10RZP7",
                "years": "ULVR",
                "sedol": "GB00B10RZP78",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.27,
                "bullAdvice": "2022-01-06 SELL",
                "sector": "Personal Care"
            },
            {
                "navMid": 0.56,
                "navPerShare": null,
                "rsi": 44.5,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ANTO",
                "stockName": "ANTOFAGASTA",
                "profit": 389,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 35.19,
                "techSum": -1,
                "percentUp": -1.63,
                "weekPercentUp": null,
                "marketCapitalisation": 13092,
                "day": "0045614",
                "week": "0045614",
                "years": "ANTO",
                "sedol": "GB0000456144",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -3.62,
                "bullAdvice": "2022-01-06 SELL",
                "sector": "Industrial Me"
            },
            {
                "navMid": 0.47,
                "navPerShare": null,
                "rsi": 44,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "JMAT",
                "stockName": "JOHNSON MATTH",
                "profit": 205,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 19.31,
                "techSum": -1,
                "percentUp": -1.65,
                "weekPercentUp": null,
                "marketCapitalisation": 3947,
                "day": "BZ4BQC7",
                "week": "BZ4BQC7",
                "years": "JMAT",
                "sedol": "GB00BZ4BQC70",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.24,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Chemicals"
            },
            {
                "navMid": 0.15,
                "navPerShare": null,
                "rsi": 53,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SVT",
                "stockName": "SEVERN TRENT",
                "profit": 212,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 32.8,
                "techSum": 0,
                "percentUp": -1.71,
                "weekPercentUp": null,
                "marketCapitalisation": 7313,
                "day": "B1FH8J7",
                "week": "B1FH8J7",
                "years": "SVT",
                "sedol": "GB00B1FH8J72",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.68,
                "bullAdvice": "2021-12-16 SELL",
                "sector": "Gas, Water an"
            },
            {
                "navMid": 0.23,
                "navPerShare": null,
                "rsi": 49,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SSE",
                "stockName": "SSE",
                "profit": 2246,
                "cash": null,
                "exDividend": "2022-01-13",
                "netNet": 0,
                "peRatio": 7.43,
                "techSum": 0,
                "percentUp": -1.72,
                "weekPercentUp": null,
                "marketCapitalisation": 17320,
                "day": "0790873",
                "week": "0790873",
                "years": "SSE",
                "sedol": "GB0007908733",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.32,
                "bullAdvice": "2022-01-05 SELL",
                "sector": "Electricity"
            },
            {
                "navMid": 0.1,
                "navPerShare": null,
                "rsi": 51,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ADM",
                "stockName": "ADMIRAL GRP",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 17.16,
                "techSum": -1,
                "percentUp": -1.75,
                "weekPercentUp": null,
                "marketCapitalisation": 9223,
                "day": "B02J639",
                "week": "B02J639",
                "years": "ADM",
                "sedol": "GB00B02J6398",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.8,
                "bullAdvice": null,
                "sector": "Non-life Insu"
            },
            {
                "navMid": -0.04,
                "navPerShare": null,
                "rsi": 51.1,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "DGE",
                "stockName": "DIAGEO",
                "profit": 2660,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 34.96,
                "techSum": 0,
                "percentUp": -1.79,
                "weekPercentUp": null,
                "marketCapitalisation": 92563,
                "day": "0237400",
                "week": "0237400",
                "years": "DGE",
                "sedol": "GB0002374006",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.47,
                "bullAdvice": "2022-01-06 BUY",
                "sector": "Beverages"
            },
            {
                "navMid": 0.35,
                "navPerShare": null,
                "rsi": 49,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "PSN",
                "stockName": "PERSIMMON",
                "profit": 638,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 14.03,
                "techSum": -1,
                "percentUp": -1.79,
                "weekPercentUp": null,
                "marketCapitalisation": 8935,
                "day": "0682538",
                "week": "0682538",
                "years": "PSN",
                "sedol": "GB0006825383",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.27,
                "bullAdvice": "2021-12-29 BUY",
                "sector": "Household Goo"
            },
            {
                "navMid": 0.08,
                "navPerShare": null,
                "rsi": 59.99,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "FERG",
                "stockName": "FERGUSON",
                "profit": 1217,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 26.83,
                "techSum": 1,
                "percentUp": -2.13,
                "weekPercentUp": null,
                "marketCapitalisation": 28592,
                "day": "BJVNSS4",
                "week": "BJVNSS4",
                "years": "FERG",
                "sedol": "JE00BJVNSS43",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.54,
                "bullAdvice": "2021-12-31 SELL",
                "sector": "Industrial Su"
            },
            {
                "navMid": -0.38,
                "navPerShare": null,
                "rsi": 50.5,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "GSK",
                "stockName": "GLAXOSMITHKLI",
                "profit": 5749,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 13.73,
                "techSum": 0,
                "percentUp": -2.18,
                "weekPercentUp": null,
                "marketCapitalisation": 79945,
                "day": "0925288",
                "week": "0925288",
                "years": "GSK",
                "sedol": "GB0009252882",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.13,
                "bullAdvice": null,
                "sector": "Pharmaceutica"
            },
            {
                "navMid": 0.39,
                "navPerShare": null,
                "rsi": 47.1,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "JD.",
                "stockName": "JD SPORTS",
                "profit": 246,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 46.2,
                "techSum": -1,
                "percentUp": -2.29,
                "weekPercentUp": null,
                "marketCapitalisation": 10977,
                "day": "BYX91H5",
                "week": "BYX91H5",
                "years": "JD.",
                "sedol": "GB00BYX91H57",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.58,
                "bullAdvice": "2022-01-04 SELL",
                "sector": "Retailers"
            },
            {
                "navMid": 0.33,
                "navPerShare": null,
                "rsi": 52.6,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "NG.",
                "stockName": "NATIONAL GRID",
                "profit": 1255,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 22.55,
                "techSum": 0,
                "percentUp": -2.59,
                "weekPercentUp": null,
                "marketCapitalisation": 38139,
                "day": "BDR05C0",
                "week": "BDR05C0",
                "years": "NG.",
                "sedol": "GB00BDR05C01",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.42,
                "bullAdvice": "2021-12-30 SELL",
                "sector": "Gas, Water an"
            },
            {
                "navMid": 0.39,
                "navPerShare": null,
                "rsi": 41.3,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "UU.",
                "stockName": "UTD. UTILITIE",
                "profit": 107,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 16.08,
                "techSum": -1,
                "percentUp": -2.9,
                "weekPercentUp": null,
                "marketCapitalisation": 7313,
                "day": "B39J2M4",
                "week": "B39J2M4",
                "years": "UU.",
                "sedol": "GB00B39J2M42",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.49,
                "bullAdvice": "2021-12-31 BUY",
                "sector": "Gas, Water an"
            },
            {
                "navMid": -0.03,
                "navPerShare": null,
                "rsi": 48.9,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "AUTO",
                "stockName": "AUTO TRAD",
                "profit": 0,
                "cash": null,
                "exDividend": "2022-01-06",
                "netNet": -0.06,
                "peRatio": 54.03,
                "techSum": -1,
                "percentUp": -2.91,
                "weekPercentUp": null,
                "marketCapitalisation": 6797,
                "day": "BVYVFW2",
                "week": "BVYVFW2",
                "years": "AUTO",
                "sedol": "GB00BVYVFW23",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.44,
                "bullAdvice": "2021-12-29 BUY",
                "sector": "Software and "
            },
            {
                "navMid": 0.21,
                "navPerShare": null,
                "rsi": 40.78,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ICP",
                "stockName": "INT.CAP.GRP",
                "profit": 457,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 13.14,
                "techSum": -1,
                "percentUp": -3.28,
                "weekPercentUp": null,
                "marketCapitalisation": 6102,
                "day": "BYT1DJ1",
                "week": "BYT1DJ1",
                "years": "ICP",
                "sedol": "GB00BYT1DJ19",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -3.91,
                "bullAdvice": "2022-01-05 SELL",
                "sector": "Investment Ba"
            },
            {
                "navMid": -0.07,
                "navPerShare": null,
                "rsi": 48,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "FLTR",
                "stockName": "FLUTTER ENT",
                "profit": 38,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 385.67,
                "techSum": -1,
                "percentUp": -3.3,
                "weekPercentUp": null,
                "marketCapitalisation": 20085,
                "day": "BWT6H89",
                "week": "BWT6H89",
                "years": "FLTR",
                "sedol": "IE00BWT6H894",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -4.41,
                "bullAdvice": "2022-01-06 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 0.01,
                "navPerShare": null,
                "rsi": 43,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SPX",
                "stockName": "SPIRAX-SARCO",
                "profit": 174,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 65.97,
                "techSum": -1,
                "percentUp": -3.57,
                "weekPercentUp": null,
                "marketCapitalisation": 11460,
                "day": "BWFGQN1",
                "week": "BWFGQN1",
                "years": "SPX",
                "sedol": "GB00BWFGQN14",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -3.57,
                "bullAdvice": "2022-01-04 SELL",
                "sector": "Industrial En"
            },
            {
                "navMid": -0.05,
                "navPerShare": null,
                "rsi": 54.1,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SGE",
                "stockName": "SAGE GRP.",
                "profit": 0,
                "cash": null,
                "exDividend": "2022-01-13",
                "netNet": 0,
                "peRatio": 31.33,
                "techSum": 1,
                "percentUp": -3.74,
                "weekPercentUp": null,
                "marketCapitalisation": 8427,
                "day": "B8C3BL0",
                "week": "B8C3BL0",
                "years": "SGE",
                "sedol": "GB00B8C3BL03",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.43,
                "bullAdvice": "2022-01-04 SELL",
                "sector": "Software and "
            },
            {
                "navMid": 0.01,
                "navPerShare": null,
                "rsi": 49.4,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RMV",
                "stockName": "RIGHTMOVE",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 60.94,
                "techSum": 0,
                "percentUp": -3.76,
                "weekPercentUp": null,
                "marketCapitalisation": 6500,
                "day": "BGDT3G2",
                "week": "BGDT3G2",
                "years": "RMV",
                "sedol": "GB00BGDT3G23",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.56,
                "bullAdvice": "2022-01-05 SELL",
                "sector": "Software and "
            },
            {
                "navMid": -0.15,
                "navPerShare": null,
                "rsi": 42,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "AZN",
                "stockName": "ASTRAZENECA",
                "profit": 2492,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 46.56,
                "techSum": -1,
                "percentUp": -4.06,
                "weekPercentUp": null,
                "marketCapitalisation": 129468,
                "day": "0989529",
                "week": "0989529",
                "years": "AZN",
                "sedol": "GB0009895292",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.51,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Pharmaceutica"
            },
            {
                "navMid": 0.05,
                "navPerShare": null,
                "rsi": 40,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "NXT",
                "stockName": "NEXT PLC",
                "profit": 287,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 34.71,
                "techSum": -2,
                "percentUp": -4.27,
                "weekPercentUp": null,
                "marketCapitalisation": 10330,
                "day": "3208986",
                "week": "3208986",
                "years": "NXT",
                "sedol": "GB0032089863",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -3.96,
                "bullAdvice": null,
                "sector": "Retailers"
            },
            {
                "navMid": 0.25,
                "navPerShare": null,
                "rsi": 33,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "HIK",
                "stockName": "HIKMA",
                "profit": 336,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 15.91,
                "techSum": -2,
                "percentUp": -4.31,
                "weekPercentUp": null,
                "marketCapitalisation": 4919,
                "day": "B0LCW08",
                "week": "B0LCW08",
                "years": "HIK",
                "sedol": "GB00B0LCW083",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.51,
                "bullAdvice": "2022-01-06 BUY",
                "sector": "Pharmaceutica"
            },
            {
                "navMid": 0.13,
                "navPerShare": null,
                "rsi": 41.5,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "OCDO",
                "stockName": "OCADO",
                "profit": -126,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -90.43,
                "techSum": -1,
                "percentUp": -5.08,
                "weekPercentUp": null,
                "marketCapitalisation": 11946,
                "day": "B3MBS74",
                "week": "B3MBS74",
                "years": "OCDO",
                "sedol": "GB00B3MBS747",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.44,
                "bullAdvice": null,
                "sector": "Personal Care"
            },
            {
                "navMid": -0.06,
                "navPerShare": null,
                "rsi": 37.7,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RTO",
                "stockName": "RENTOKIL INIT",
                "profit": 186,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 54.5,
                "techSum": -2,
                "percentUp": -5.36,
                "weekPercentUp": null,
                "marketCapitalisation": 10182,
                "day": "B082RF1",
                "week": "B082RF1",
                "years": "RTO",
                "sedol": "GB00B082RF11",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.37,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Industrial Su"
            },
            {
                "navMid": -0.05,
                "navPerShare": null,
                "rsi": 37,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BNZL",
                "stockName": "BUNZL",
                "profit": 430,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 21.56,
                "techSum": -1,
                "percentUp": -5.57,
                "weekPercentUp": null,
                "marketCapitalisation": 9370,
                "day": "B0744B3",
                "week": "B0744B3",
                "years": "BNZL",
                "sedol": "GB00B0744B38",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -3.22,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "General Indus"
            },
            {
                "navMid": 0.52,
                "navPerShare": null,
                "rsi": 34.6,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "FRES",
                "stockName": "FRESNILLO",
                "profit": 292,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 22.03,
                "techSum": -2,
                "percentUp": -5.67,
                "weekPercentUp": null,
                "marketCapitalisation": 6047,
                "day": "B2QPKJ1",
                "week": "B2QPKJ1",
                "years": "FRES",
                "sedol": "GB00B2QPKJ12",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -4.43,
                "bullAdvice": "2022-01-06 BUY",
                "sector": "Precious Meta"
            },
            {
                "navMid": 0.04,
                "navPerShare": null,
                "rsi": 36,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "CRDA",
                "stockName": "CRODA INTL.",
                "profit": 202,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 61.28,
                "techSum": -1,
                "percentUp": -6.6,
                "weekPercentUp": null,
                "marketCapitalisation": 13260,
                "day": "BJFFLV0",
                "week": "BJFFLV0",
                "years": "CRDA",
                "sedol": "GB00BJFFLV09",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -3.11,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Chemicals"
            },
            {
                "navMid": 0,
                "navPerShare": null,
                "rsi": 40,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "HLMA",
                "stockName": "HALMA",
                "profit": 203,
                "cash": null,
                "exDividend": "2021-12-23",
                "netNet": 0,
                "peRatio": 55.9,
                "techSum": -1,
                "percentUp": -6.72,
                "weekPercentUp": null,
                "marketCapitalisation": 11416,
                "day": "0405207",
                "week": "0405207",
                "years": "HLMA",
                "sedol": "GB0004052071",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -4.92,
                "bullAdvice": "2022-01-05 SELL",
                "sector": "Electronic an"
            },
            {
                "navMid": -0.1,
                "navPerShare": null,
                "rsi": 40,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "EXPN",
                "stockName": "EXPERIAN",
                "profit": 615,
                "cash": null,
                "exDividend": "2022-01-06",
                "netNet": 0,
                "peRatio": 53.18,
                "techSum": -1,
                "percentUp": -6.96,
                "weekPercentUp": null,
                "marketCapitalisation": 31489,
                "day": "B19NLV4",
                "week": "B19NLV4",
                "years": "EXPN",
                "sedol": "GB00B19NLV48",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -5.07,
                "bullAdvice": "2022-01-05 BUY",
                "sector": "Industrial Su"
            },
            {
                "navMid": 0.47,
                "navPerShare": null,
                "rsi": 31,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "REL",
                "stockName": "RELX",
                "profit": 1224,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 35.21,
                "techSum": -1,
                "percentUp": -7.14,
                "weekPercentUp": null,
                "marketCapitalisation": 43280,
                "day": "B2B0DG9",
                "week": "B2B0DG9",
                "years": "REL",
                "sedol": "GB00B2B0DG97",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -5.12,
                "bullAdvice": "2022-01-04 SELL",
                "sector": "Media"
            },
            {
                "navMid": 0.34,
                "navPerShare": null,
                "rsi": 29.6,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "POLY",
                "stockName": "POLYMETAL INT",
                "profit": 847,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 7.11,
                "techSum": -2,
                "percentUp": -7.68,
                "weekPercentUp": null,
                "marketCapitalisation": 5686,
                "day": "B6T5S47",
                "week": "B6T5S47",
                "years": "POLY",
                "sedol": "JE00B6T5S470",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -3.95,
                "bullAdvice": "2022-01-04 SELL",
                "sector": "Precious Meta"
            },
            {
                "navMid": 0.03,
                "navPerShare": null,
                "rsi": 34,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "AVV",
                "stockName": "AVEVA GRP",
                "profit": 0,
                "cash": null,
                "exDividend": "2022-01-06",
                "netNet": 0,
                "peRatio": 276.21,
                "techSum": -2,
                "percentUp": -7.88,
                "weekPercentUp": null,
                "marketCapitalisation": 9450,
                "day": "BBG9VN7",
                "week": "BBG9VN7",
                "years": "AVV",
                "sedol": "GB00BBG9VN75",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -6.21,
                "bullAdvice": "2021-12-30 SELL",
                "sector": "Software and "
            },
            {
                "navMid": -0.07,
                "navPerShare": null,
                "rsi": 30.1,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "JET",
                "stockName": "JUST EAT TAKE",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -38,
                "techSum": -1,
                "percentUp": -9.16,
                "weekPercentUp": null,
                "marketCapitalisation": 7846,
                "day": "1201570",
                "week": "1201570",
                "years": "JET",
                "sedol": "NL0012015705",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -4.56,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Software and "
            }
        ]
    )

)
    //  return next();
});


module.exports = router;