'use strict';
var express = require('express');
var router = express.Router();
var app = express();
var path = require('path');
//var pthv = require('./pthv');

/* GET home page. */

router.get('/', (req, res) => {
    console.log("in here a");

    console.log(req.path);
    console.log(req.params);
    console.log(req.params.useridname);
    // app.use('/pthv/:useridname', pthv);
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify(

        [
            {
                "navMid": 0.47,
                "navPerShare": null,
                "rsi": 67.8,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "EZJ",
                "stockName": "EASYJET",
                "profit": -858,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -3.88,
                "techSum": 1,
                "percentUp": 11.96,
                "weekPercentUp": null,
                "marketCapitalisation": 2818,
                "day": "B7KR2P8",
                "week": "B7KR2P8",
                "years": "EZJ",
                "sedol": "GB00B7KR2P84",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.3,
                "bullAdvice": "2022-01-05 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 1.06,
                "navPerShare": null,
                "rsi": 65.86,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "IAG",
                "stockName": "INTL CONSOL A",
                "profit": -6154,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -0.91,
                "techSum": 1,
                "percentUp": 11.81,
                "weekPercentUp": null,
                "marketCapitalisation": 7977,
                "day": "7754201",
                "week": "7754201",
                "years": "IAG",
                "sedol": "ES0177542018",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.87,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": -0.27,
                "navPerShare": null,
                "rsi": 66.85,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "MRO",
                "stockName": "MELROSE IND",
                "profit": -526,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -13.77,
                "techSum": 1,
                "percentUp": 7.65,
                "weekPercentUp": null,
                "marketCapitalisation": 8174,
                "day": "BNR5MZ7",
                "week": "BNR5MZ7",
                "years": "MRO",
                "sedol": "GB00BNR5MZ78",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.6,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "General Indus"
            },
            {
                "navMid": 0,
                "navPerShare": null,
                "rsi": 68,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "IHG",
                "stockName": "INTERCON. HOT",
                "profit": -203,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -48.28,
                "techSum": 1,
                "percentUp": 6.52,
                "weekPercentUp": null,
                "marketCapitalisation": 9274,
                "day": "BHJYC05",
                "week": "BHJYC05",
                "years": "IHG",
                "sedol": "GB00BHJYC057",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.34,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 1.02,
                "navPerShare": null,
                "rsi": 64.97,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "LLOY",
                "stockName": "LLOYDS GRP.",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 42.23,
                "techSum": 1,
                "percentUp": 6.25,
                "weekPercentUp": null,
                "marketCapitalisation": 35964,
                "day": "0870612",
                "week": "0870612",
                "years": "LLOY",
                "sedol": "GB0008706128",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.97,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Banks"
            },
            {
                "navMid": 0,
                "navPerShare": null,
                "rsi": 57.78,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RR.",
                "stockName": "ROLLS-ROYCE H",
                "profit": -1315,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -2.43,
                "techSum": 1,
                "percentUp": 5.74,
                "weekPercentUp": null,
                "marketCapitalisation": 10756,
                "day": "B63H849",
                "week": "B63H849",
                "years": "RR.",
                "sedol": "GB00B63H8491",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.55,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Aerospace and"
            },
            {
                "navMid": 1.21,
                "navPerShare": null,
                "rsi": 62.9,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RDSB",
                "stockName": "RDS 'B'",
                "profit": -16906,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -8.45,
                "techSum": 2,
                "percentUp": 5.67,
                "weekPercentUp": null,
                "marketCapitalisation": 137079,
                "day": "B03MM40",
                "week": "B03MM40",
                "years": "RDSB",
                "sedol": "GB00B03MM408",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.57,
                "bullAdvice": "2022-01-05 BUY",
                "sector": "Oil, Gas and "
            },
            {
                "navMid": 0.85,
                "navPerShare": null,
                "rsi": 64,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "WTB",
                "stockName": "WHITBREAD",
                "profit": -907,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -6.55,
                "techSum": 1,
                "percentUp": 5.62,
                "weekPercentUp": null,
                "marketCapitalisation": 6374,
                "day": "B1KJJ40",
                "week": "B1KJJ40",
                "years": "WTB",
                "sedol": "GB00B1KJJ408",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.74,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 1.21,
                "navPerShare": null,
                "rsi": 62.7,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RDSA",
                "stockName": "RDS 'A'",
                "profit": -16906,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -8.44,
                "techSum": 2,
                "percentUp": 5.61,
                "weekPercentUp": null,
                "marketCapitalisation": 131069,
                "day": "B03MLX2",
                "week": "B03MLX2",
                "years": "RDSA",
                "sedol": "GB00B03MLX29",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.63,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Oil, Gas and "
            },
            {
                "navMid": 1.16,
                "navPerShare": null,
                "rsi": 59.22,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "CCL",
                "stockName": "CARNIVAL",
                "profit": -6902,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -1.49,
                "techSum": 1,
                "percentUp": 5.6,
                "weekPercentUp": null,
                "marketCapitalisation": 17064,
                "day": "3121522",
                "week": "3121522",
                "years": "CCL",
                "sedol": "GB0031215220",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.38,
                "bullAdvice": "2022-01-05 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": 1,
                "navPerShare": null,
                "rsi": 60.96,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BP.",
                "stockName": "BP",
                "profit": 3155,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -4.82,
                "techSum": 2,
                "percentUp": 5.52,
                "weekPercentUp": null,
                "marketCapitalisation": 71803,
                "day": "0798059",
                "week": "0798059",
                "years": "BP.",
                "sedol": "GB0007980591",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.13,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Oil, Gas and "
            },
            {
                "navMid": 1.69,
                "navPerShare": null,
                "rsi": 65.48,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BARC",
                "stockName": "BARCLAYS",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.01,
                "peRatio": 22.49,
                "techSum": 1,
                "percentUp": 4.77,
                "weekPercentUp": null,
                "marketCapitalisation": 33638,
                "day": "3134865",
                "week": "3134865",
                "years": "BARC",
                "sedol": "GB0031348658",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.51,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Banks"
            },
            {
                "navMid": -0.62,
                "navPerShare": null,
                "rsi": 64.2,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "INF",
                "stockName": "INFORMA",
                "profit": -1042,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -7.4,
                "techSum": 1,
                "percentUp": 4.63,
                "weekPercentUp": null,
                "marketCapitalisation": 8165,
                "day": "BMJ6DW5",
                "week": "BMJ6DW5",
                "years": "INF",
                "sedol": "GB00BMJ6DW54",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.09,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Media"
            },
            {
                "navMid": 1.85,
                "navPerShare": null,
                "rsi": 69.31,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "HSBA",
                "stockName": "HSBC HLDGS.UK",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.01,
                "peRatio": 33.59,
                "techSum": 1,
                "percentUp": 4.46,
                "weekPercentUp": null,
                "marketCapitalisation": 95655,
                "day": "0540528",
                "week": "0540528",
                "years": "HSBA",
                "sedol": "GB0005405286",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.42,
                "bullAdvice": "2021-12-01 BUY",
                "sector": "Banks"
            },
            {
                "navMid": 0.5,
                "navPerShare": null,
                "rsi": 69.4,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "AAL",
                "stockName": "ANGLO AMERICA",
                "profit": 1629,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 25.66,
                "techSum": 2,
                "percentUp": 4.39,
                "weekPercentUp": null,
                "marketCapitalisation": 43374,
                "day": "B1XZS82",
                "week": "B1XZS82",
                "years": "AAL",
                "sedol": "GB00B1XZS820",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 2.84,
                "bullAdvice": "2022-01-05 BUY",
                "sector": "Industrial Me"
            },
            {
                "navMid": 1.29,
                "navPerShare": null,
                "rsi": 68.2,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "NWG",
                "stockName": "ROYAL BANK SC",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.01,
                "peRatio": -38.29,
                "techSum": 1,
                "percentUp": 4.39,
                "weekPercentUp": null,
                "marketCapitalisation": 27481,
                "day": "B7T7721",
                "week": "B7T7721",
                "years": "NWG",
                "sedol": "GB00B7T77214",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.69,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Banks"
            },
            {
                "navMid": -0.07,
                "navPerShare": null,
                "rsi": 58.92,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "FLTR",
                "stockName": "FLUTTER ENT",
                "profit": 38,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 403.93,
                "techSum": 1,
                "percentUp": 4.37,
                "weekPercentUp": null,
                "marketCapitalisation": 20748,
                "day": "BWT6H89",
                "week": "BWT6H89",
                "years": "FLTR",
                "sedol": "IE00BWT6H894",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.91,
                "bullAdvice": "2021-12-31 BUY",
                "sector": "Travel and Le"
            },
            {
                "navMid": -0.65,
                "navPerShare": null,
                "rsi": 76.27,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "CNA",
                "stockName": "CENTRICA",
                "profit": -274,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 105.03,
                "techSum": 1,
                "percentUp": 4.23,
                "weekPercentUp": null,
                "marketCapitalisation": 4323,
                "day": "B033F22",
                "week": "B033F22",
                "years": "CNA",
                "sedol": "GB00B033F229",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Gas, Water an"
            },
            {
                "navMid": -0.05,
                "navPerShare": null,
                "rsi": 67.9,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "CPG",
                "stockName": "COMPASS GROUP",
                "profit": 357,
                "cash": null,
                "exDividend": "2022-01-20",
                "netNet": 0,
                "peRatio": 85,
                "techSum": 1,
                "percentUp": 4,
                "weekPercentUp": null,
                "marketCapitalisation": 30329,
                "day": "BD6K457",
                "week": "BD6K457",
                "years": "CPG",
                "sedol": "GB00BD6K4575",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.24,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Consumer Serv"
            },
            {
                "navMid": 3.07,
                "navPerShare": null,
                "rsi": 62.4,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "STAN",
                "stockName": "STAND.CHART.",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.01,
                "peRatio": 60.31,
                "techSum": 1,
                "percentUp": 3.95,
                "weekPercentUp": null,
                "marketCapitalisation": 14354,
                "day": "0408284",
                "week": "0408284",
                "years": "STAN",
                "sedol": "GB0004082847",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.08,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Banks"
            },
            {
                "navMid": 0.13,
                "navPerShare": null,
                "rsi": 59.5,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BRBY",
                "stockName": "BURBERRY GRP",
                "profit": 376,
                "cash": null,
                "exDividend": "2021-12-16",
                "netNet": 0,
                "peRatio": 20.01,
                "techSum": 1,
                "percentUp": 3.8,
                "weekPercentUp": null,
                "marketCapitalisation": 7535,
                "day": "3174300",
                "week": "3174300",
                "years": "BRBY",
                "sedol": "GB0031743007",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.14,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Personal Good"
            },
            {
                "navMid": 0.59,
                "navPerShare": null,
                "rsi": 64.36,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RIO",
                "stockName": "RIO TINTO",
                "profit": 7618,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 11.36,
                "techSum": 1,
                "percentUp": 3.31,
                "weekPercentUp": null,
                "marketCapitalisation": 81511,
                "day": "0718875",
                "week": "0718875",
                "years": "RIO",
                "sedol": "GB0007188757",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.98,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Industrial Me"
            },
            {
                "navMid": -0.16,
                "navPerShare": null,
                "rsi": 57.95,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ITV",
                "stockName": "ITV",
                "profit": 285,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 16.13,
                "techSum": 1,
                "percentUp": 3.16,
                "weekPercentUp": null,
                "marketCapitalisation": 4609,
                "day": "3398649",
                "week": "3398649",
                "years": "ITV",
                "sedol": "GB0033986497",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.44,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Media"
            },
            {
                "navMid": 0,
                "navPerShare": null,
                "rsi": 63.4,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "MNG",
                "stockName": "M&G PLC",
                "profit": -55,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 4.67,
                "techSum": 1,
                "percentUp": 2.99,
                "weekPercentUp": null,
                "marketCapitalisation": 5391,
                "day": "BKFB1C6",
                "week": "BKFB1C6",
                "years": "MNG",
                "sedol": "GB00BKFB1C65",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.96,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Investment Ba"
            },
            {
                "navMid": 0.74,
                "navPerShare": null,
                "rsi": 67.7,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "AV.",
                "stockName": "AVIVA",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 6.06,
                "techSum": 1,
                "percentUp": 2.9,
                "weekPercentUp": null,
                "marketCapitalisation": 16723,
                "day": "0216238",
                "week": "0216238",
                "years": "AV.",
                "sedol": "GB0002162385",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.23,
                "bullAdvice": "2021-12-14 BUY",
                "sector": "Life Insuranc"
            },
            {
                "navMid": 0.65,
                "navPerShare": null,
                "rsi": 65.06,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "GLEN",
                "stockName": "GLENCORE",
                "profit": -1484,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -38.26,
                "techSum": 2,
                "percentUp": 2.75,
                "weekPercentUp": null,
                "marketCapitalisation": 51848,
                "day": "B4T3BW6",
                "week": "B4T3BW6",
                "years": "GLEN",
                "sedol": "JE00B4T3BW64",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.66,
                "bullAdvice": "2022-01-05 BUY",
                "sector": "Industrial Me"
            },
            {
                "navMid": 0.06,
                "navPerShare": null,
                "rsi": 61.2,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BT.A",
                "stockName": "BT GROUP",
                "profit": 1472,
                "cash": null,
                "exDividend": "2021-12-30",
                "netNet": 0,
                "peRatio": 11.88,
                "techSum": 2,
                "percentUp": 2.64,
                "weekPercentUp": null,
                "marketCapitalisation": 17431,
                "day": "3091357",
                "week": "3091357",
                "years": "BT.A",
                "sedol": "GB0030913577",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.15,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Telecommunica"
            },
            {
                "navMid": 0.3,
                "navPerShare": null,
                "rsi": 53.6,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "PSON",
                "stockName": "PEARSON",
                "profit": 310,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 14.91,
                "techSum": 0,
                "percentUp": 2.52,
                "weekPercentUp": null,
                "marketCapitalisation": 4624,
                "day": "0677608",
                "week": "0677608",
                "years": "PSON",
                "sedol": "GB0006776081",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.88,
                "bullAdvice": "2021-12-09 BUY",
                "sector": "Media"
            },
            {
                "navMid": 0.42,
                "navPerShare": null,
                "rsi": 68,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BHP",
                "stockName": "BHP GROUP",
                "profit": 8402,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 14.04,
                "techSum": 2,
                "percentUp": 2.47,
                "weekPercentUp": null,
                "marketCapitalisation": 114642,
                "day": "BH0P3Z9",
                "week": "BH0P3Z9",
                "years": "BHP",
                "sedol": "GB00BH0P3Z91",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 2.06,
                "bullAdvice": "2021-12-14 BUY",
                "sector": "Industrial Me"
            },
            {
                "navMid": 0.54,
                "navPerShare": null,
                "rsi": 51.3,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ANTO",
                "stockName": "ANTOFAGASTA",
                "profit": 389,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 36.45,
                "techSum": 0,
                "percentUp": 2.47,
                "weekPercentUp": null,
                "marketCapitalisation": 13526,
                "day": "0045614",
                "week": "0045614",
                "years": "ANTO",
                "sedol": "GB0000456144",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.66,
                "bullAdvice": "2021-12-23 BUY",
                "sector": "Industrial Me"
            },
            {
                "navMid": 0.07,
                "navPerShare": null,
                "rsi": 64.18,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SN.",
                "stockName": "SMITH&NEPHEW",
                "profit": 470,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 35.06,
                "techSum": 1,
                "percentUp": 2.25,
                "weekPercentUp": null,
                "marketCapitalisation": 11600,
                "day": "0922320",
                "week": "0922320",
                "years": "SN.",
                "sedol": "GB0009223206",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.84,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Medical Equip"
            },
            {
                "navMid": -0.24,
                "navPerShare": null,
                "rsi": 70.3,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "WPP",
                "stockName": "WPP",
                "profit": -2974,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -4.78,
                "techSum": 2,
                "percentUp": 2.17,
                "weekPercentUp": null,
                "marketCapitalisation": 13915,
                "day": "B8KF9B4",
                "week": "B8KF9B4",
                "years": "WPP",
                "sedol": "JE00B8KF9B49",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.74,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Media"
            },
            {
                "navMid": 0.07,
                "navPerShare": null,
                "rsi": 65,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "CCH",
                "stockName": "COCACOLA HBC ",
                "profit": 369,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 25.71,
                "techSum": 1,
                "percentUp": 2.1,
                "weekPercentUp": null,
                "marketCapitalisation": 9647,
                "day": "9825130",
                "week": "9825130",
                "years": "CCH",
                "sedol": "CH0198251305",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.66,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Beverages"
            },
            {
                "navMid": -0.85,
                "navPerShare": null,
                "rsi": 63.8,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BATS",
                "stockName": "BR.AMER.TOB.",
                "profit": 6400,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 9.97,
                "techSum": 1,
                "percentUp": 2.08,
                "weekPercentUp": null,
                "marketCapitalisation": 64031,
                "day": "0287580",
                "week": "0287580",
                "years": "BATS",
                "sedol": "GB0002875804",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.36,
                "bullAdvice": "2021-12-23 SELL",
                "sector": "Tobacco"
            },
            {
                "navMid": 0.25,
                "navPerShare": null,
                "rsi": 74.65,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "TSCO",
                "stockName": "TESCO",
                "profit": 717,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 4.65,
                "techSum": 2,
                "percentUp": 2.07,
                "weekPercentUp": null,
                "marketCapitalisation": 22940,
                "day": "BLGZ986",
                "week": "BLGZ986",
                "years": "TSCO",
                "sedol": "GB00BLGZ9862",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.01,
                "bullAdvice": "2021-12-30 BUY",
                "sector": "Personal Care"
            },
            {
                "navMid": 0.46,
                "navPerShare": null,
                "rsi": 46,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "JMAT",
                "stockName": "JOHNSON MATTH",
                "profit": 205,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 19.4,
                "techSum": 0,
                "percentUp": 2.04,
                "weekPercentUp": null,
                "marketCapitalisation": 3998,
                "day": "BZ4BQC7",
                "week": "BZ4BQC7",
                "years": "JMAT",
                "sedol": "GB00BZ4BQC70",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.14,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Chemicals"
            },
            {
                "navMid": 0.48,
                "navPerShare": null,
                "rsi": 62,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ABF",
                "stockName": "A.B.FOOD",
                "profit": 478,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 34,
                "techSum": 1,
                "percentUp": 1.97,
                "weekPercentUp": null,
                "marketCapitalisation": 16285,
                "day": "0673123",
                "week": "0673123",
                "years": "ABF",
                "sedol": "GB0006731235",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.69,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Food Producer"
            },
            {
                "navMid": 0.51,
                "navPerShare": null,
                "rsi": 61.76,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "LGEN",
                "stockName": "LEGAL&GEN.",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 11.2,
                "techSum": 1,
                "percentUp": 1.86,
                "weekPercentUp": null,
                "marketCapitalisation": 18040,
                "day": "0560399",
                "week": "0560399",
                "years": "LGEN",
                "sedol": "GB0005603997",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.82,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Life Insuranc"
            },
            {
                "navMid": 0.03,
                "navPerShare": null,
                "rsi": 62.34,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SMDS",
                "stockName": "SMITH(DS)",
                "profit": 182,
                "cash": null,
                "exDividend": "2022-04-07",
                "netNet": 0,
                "peRatio": 28.02,
                "techSum": 1,
                "percentUp": 1.8,
                "weekPercentUp": null,
                "marketCapitalisation": 5464,
                "day": "0822011",
                "week": "0822011",
                "years": "SMDS",
                "sedol": "GB0008220112",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.51,
                "bullAdvice": "2021-12-23 BUY",
                "sector": "General Indus"
            },
            {
                "navMid": 0.26,
                "navPerShare": null,
                "rsi": 54.46,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "VOD",
                "stockName": "VODAFONE GRP.",
                "profit": 100,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 352.69,
                "techSum": 1,
                "percentUp": 1.77,
                "weekPercentUp": null,
                "marketCapitalisation": 32102,
                "day": "BH4HKS3",
                "week": "BH4HKS3",
                "years": "VOD",
                "sedol": "GB00BH4HKS39",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-30 SELL",
                "sector": "Telecommunica"
            },
            {
                "navMid": 0.27,
                "navPerShare": null,
                "rsi": 66,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "CRH",
                "stockName": "CRH",
                "profit": 875,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 38.01,
                "techSum": 1,
                "percentUp": 1.77,
                "weekPercentUp": null,
                "marketCapitalisation": 31191,
                "day": "0182704",
                "week": "0182704",
                "years": "CRH",
                "sedol": "IE0001827041",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.15,
                "bullAdvice": "2021-12-07 BUY",
                "sector": "Construction "
            },
            {
                "navMid": 0.33,
                "navPerShare": null,
                "rsi": 60.73,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "MNDI",
                "stockName": "MONDI",
                "profit": 517,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 17.26,
                "techSum": 1,
                "percentUp": 1.77,
                "weekPercentUp": null,
                "marketCapitalisation": 9075,
                "day": "B1CRLC4",
                "week": "B1CRLC4",
                "years": "MNDI",
                "sedol": "GB00B1CRLC47",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.73,
                "bullAdvice": "2021-12-29 BUY",
                "sector": "Industrial Ma"
            },
            {
                "navMid": 0.05,
                "navPerShare": null,
                "rsi": 70.9,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "STJ",
                "stockName": "ST.JAMES'S PL",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 35.17,
                "techSum": 1,
                "percentUp": 1.65,
                "weekPercentUp": null,
                "marketCapitalisation": 9314,
                "day": "0766937",
                "week": "0766937",
                "years": "STJ",
                "sedol": "GB0007669376",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.34,
                "bullAdvice": "2021-12-16 BUY",
                "sector": "Life Insuranc"
            },
            {
                "navMid": 0.38,
                "navPerShare": null,
                "rsi": 54.5,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "JD.",
                "stockName": "JD SPORTS",
                "profit": 246,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 47.51,
                "techSum": 1,
                "percentUp": 1.63,
                "weekPercentUp": null,
                "marketCapitalisation": 2259,
                "day": "BYX91H5",
                "week": "BYX91H5",
                "years": "JD.",
                "sedol": "GB00BYX91H57",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.84,
                "bullAdvice": "2022-01-04 SELL",
                "sector": "Retailers"
            },
            {
                "navMid": 0.28,
                "navPerShare": null,
                "rsi": 57.6,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "PHNX",
                "stockName": "PHOENIX GRP H",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 7.19,
                "techSum": 1,
                "percentUp": 1.38,
                "weekPercentUp": null,
                "marketCapitalisation": 6593,
                "day": "BGXQNP2",
                "week": "BGXQNP2",
                "years": "PHNX",
                "sedol": "GB00BGXQNP29",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.08,
                "bullAdvice": null,
                "sector": "Life Insuranc"
            },
            {
                "navMid": -0.85,
                "navPerShare": null,
                "rsi": 67.2,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "IMB",
                "stockName": "IMP.BRANDS",
                "profit": 2834,
                "cash": null,
                "exDividend": "2022-02-17",
                "netNet": 0,
                "peRatio": 5.5,
                "techSum": 1,
                "percentUp": 1.26,
                "weekPercentUp": null,
                "marketCapitalisation": 15602,
                "day": "0454492",
                "week": "0454492",
                "years": "IMB",
                "sedol": "GB0004544929",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.25,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Tobacco"
            },
            {
                "navMid": 0.06,
                "navPerShare": null,
                "rsi": 62.01,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "DCC",
                "stockName": "DCC",
                "profit": 293,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 20.79,
                "techSum": 1,
                "percentUp": 1.23,
                "weekPercentUp": null,
                "marketCapitalisation": 6088,
                "day": "0242493",
                "week": "0242493",
                "years": "DCC",
                "sedol": "IE0002424939",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.38,
                "bullAdvice": "2021-12-02 BUY",
                "sector": "Industrial Su"
            },
            {
                "navMid": 0.13,
                "navPerShare": null,
                "rsi": 67.18,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SMIN",
                "stockName": "SMITHS GROUP",
                "profit": 156,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 22.69,
                "techSum": 2,
                "percentUp": 1.19,
                "weekPercentUp": null,
                "marketCapitalisation": 6447,
                "day": "B1WY233",
                "week": "B1WY233",
                "years": "SMIN",
                "sedol": "GB00B1WY2338",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.34,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "General Indus"
            },
            {
                "navMid": 0.04,
                "navPerShare": null,
                "rsi": 46.9,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "PRU",
                "stockName": "PRUDENTIAL",
                "profit": 403,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 21.62,
                "techSum": -1,
                "percentUp": 1.1,
                "weekPercentUp": null,
                "marketCapitalisation": 33859,
                "day": "0709954",
                "week": "0709954",
                "years": "PRU",
                "sedol": "GB0007099541",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.31,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Life Insuranc"
            },
            {
                "navMid": 0.11,
                "navPerShare": null,
                "rsi": 56.48,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "EVR",
                "stockName": "EVRAZ",
                "profit": 661,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 14.49,
                "techSum": 2,
                "percentUp": 1.07,
                "weekPercentUp": null,
                "marketCapitalisation": 8991,
                "day": "B71N6K8",
                "week": "B71N6K8",
                "years": "EVR",
                "sedol": "GB00B71N6K86",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.74,
                "bullAdvice": "2021-12-14 BUY",
                "sector": "Industrial Me"
            },
            {
                "navMid": 0.52,
                "navPerShare": null,
                "rsi": 66.3,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BDEV",
                "stockName": "BARRATT DEVEL",
                "profit": 660,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 11.67,
                "techSum": 1,
                "percentUp": 1.07,
                "weekPercentUp": null,
                "marketCapitalisation": 7715,
                "day": "0081180",
                "week": "0081180",
                "years": "BDEV",
                "sedol": "GB0000811801",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.33,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Household Goo"
            },
            {
                "navMid": 0.05,
                "navPerShare": null,
                "rsi": 54,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "AHT",
                "stockName": "ASHTEAD GRP.",
                "profit": 697,
                "cash": null,
                "exDividend": "2022-01-13",
                "netNet": 0,
                "peRatio": 39.83,
                "techSum": 2,
                "percentUp": 0.89,
                "weekPercentUp": null,
                "marketCapitalisation": 27857,
                "day": "0053673",
                "week": "0053673",
                "years": "AHT",
                "sedol": "GB0000536739",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.37,
                "bullAdvice": "2021-12-23 BUY",
                "sector": "Industrial Tr"
            },
            {
                "navMid": 1.09,
                "navPerShare": null,
                "rsi": 52.25,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SBRY",
                "stockName": "SAINSBURY(J)",
                "profit": -287,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -21.52,
                "techSum": 1,
                "percentUp": 0.54,
                "weekPercentUp": null,
                "marketCapitalisation": 6266,
                "day": "B019KW7",
                "week": "B019KW7",
                "years": "SBRY",
                "sedol": "GB00B019KW72",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 1.6,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Personal Care"
            },
            {
                "navMid": -0.02,
                "navPerShare": null,
                "rsi": 60,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ITRK",
                "stockName": "INTERTEK GROU",
                "profit": 247,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 37.11,
                "techSum": 1,
                "percentUp": 0.54,
                "weekPercentUp": null,
                "marketCapitalisation": 9199,
                "day": "3163836",
                "week": "3163836",
                "years": "ITRK",
                "sedol": "GB0031638363",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.63,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Industrial Su"
            },
            {
                "navMid": -0.02,
                "navPerShare": null,
                "rsi": 60.3,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "AUTO",
                "stockName": "AUTO TRAD",
                "profit": 0,
                "cash": null,
                "exDividend": "2022-01-06",
                "netNet": -0.06,
                "peRatio": 55.56,
                "techSum": 1,
                "percentUp": 0.48,
                "weekPercentUp": null,
                "marketCapitalisation": 7111,
                "day": "BVYVFW2",
                "week": "BVYVFW2",
                "years": "AUTO",
                "sedol": "GB00BVYVFW23",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.06,
                "bullAdvice": "2021-12-29 BUY",
                "sector": "Software and "
            },
            {
                "navMid": -0.1,
                "navPerShare": null,
                "rsi": 59.86,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "MGGT",
                "stockName": "MEGGITT",
                "profit": -314,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -18.41,
                "techSum": 1,
                "percentUp": 0.41,
                "weekPercentUp": null,
                "marketCapitalisation": 5810,
                "day": "0575809",
                "week": "0575809",
                "years": "MGGT",
                "sedol": "GB0005758098",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.06,
                "bullAdvice": "2021-12-29 BUY",
                "sector": "Aerospace and"
            },
            {
                "navMid": 0.08,
                "navPerShare": null,
                "rsi": 73,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "FERG",
                "stockName": "FERGUSON",
                "profit": 1217,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 27.51,
                "techSum": 1,
                "percentUp": 0.16,
                "weekPercentUp": null,
                "marketCapitalisation": 29759,
                "day": "BJVNSS4",
                "week": "BJVNSS4",
                "years": "FERG",
                "sedol": "JE00BJVNSS43",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.05,
                "bullAdvice": "2021-12-31 SELL",
                "sector": "Industrial Su"
            },
            {
                "navMid": -0.28,
                "navPerShare": null,
                "rsi": 48,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BA.",
                "stockName": "BAE SYSTEMS P",
                "profit": 1476,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 13.44,
                "techSum": -1,
                "percentUp": 0.1,
                "weekPercentUp": null,
                "marketCapitalisation": 17656,
                "day": "0263494",
                "week": "0263494",
                "years": "BA.",
                "sedol": "GB0002634946",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.18,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Aerospace and"
            },
            {
                "navMid": 0.57,
                "navPerShare": null,
                "rsi": 69.23,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "TW.",
                "stockName": "TAYLOR WIMPEY",
                "profit": 674,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 28.24,
                "techSum": 1,
                "percentUp": 0,
                "weekPercentUp": null,
                "marketCapitalisation": 6487,
                "day": "0878230",
                "week": "0878230",
                "years": "TW.",
                "sedol": "GB0008782301",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.13,
                "bullAdvice": "2021-11-24 BUY",
                "sector": "Household Goo"
            },
            {
                "navMid": -0.17,
                "navPerShare": null,
                "rsi": 51.3,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ULVR",
                "stockName": "UNILEVER",
                "profit": 4961,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 20.6,
                "techSum": -1,
                "percentUp": -0.16,
                "weekPercentUp": null,
                "marketCapitalisation": 101599,
                "day": "B10RZP7",
                "week": "B10RZP7",
                "years": "ULVR",
                "sedol": "GB00B10RZP78",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.58,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Personal Care"
            },
            {
                "navMid": 1.55,
                "navPerShare": null,
                "rsi": 57.99,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "LAND",
                "stockName": "LAND SECS.",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": -0.04,
                "peRatio": -4.06,
                "techSum": 1,
                "percentUp": -0.26,
                "weekPercentUp": null,
                "marketCapitalisation": 5694,
                "day": "BYW0PQ6",
                "week": "BYW0PQ6",
                "years": "LAND",
                "sedol": "GB00BYW0PQ60",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.63,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Real Estate I"
            },
            {
                "navMid": -0.04,
                "navPerShare": null,
                "rsi": 61.32,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "DGE",
                "stockName": "DIAGEO",
                "profit": 2660,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 35.7,
                "techSum": 1,
                "percentUp": -0.47,
                "weekPercentUp": null,
                "marketCapitalisation": 94982,
                "day": "0237400",
                "week": "0237400",
                "years": "DGE",
                "sedol": "GB0002374006",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.72,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "Beverages"
            },
            {
                "navMid": 0.21,
                "navPerShare": null,
                "rsi": 49,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ICP",
                "stockName": "INT.CAP.GRP",
                "profit": 457,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 13.58,
                "techSum": -1,
                "percentUp": -0.54,
                "weekPercentUp": null,
                "marketCapitalisation": 6322,
                "day": "BYT1DJ1",
                "week": "BYT1DJ1",
                "years": "ICP",
                "sedol": "GB00BYT1DJ19",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.96,
                "bullAdvice": "2022-01-05 SELL",
                "sector": "Investment Ba"
            },
            {
                "navMid": 0.34,
                "navPerShare": null,
                "rsi": 59.81,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "PSN",
                "stockName": "PERSIMMON",
                "profit": 638,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 14.36,
                "techSum": 1,
                "percentUp": -0.55,
                "weekPercentUp": null,
                "marketCapitalisation": 9181,
                "day": "0682538",
                "week": "0682538",
                "years": "PSN",
                "sedol": "GB0006825383",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.47,
                "bullAdvice": "2021-12-29 BUY",
                "sector": "Household Goo"
            },
            {
                "navMid": 0.04,
                "navPerShare": null,
                "rsi": 50,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "NXT",
                "stockName": "NEXT PLC",
                "profit": 287,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 36,
                "techSum": 1,
                "percentUp": -0.6,
                "weekPercentUp": null,
                "marketCapitalisation": 10686,
                "day": "3208986",
                "week": "3208986",
                "years": "NXT",
                "sedol": "GB0032089863",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.47,
                "bullAdvice": "2022-01-05 BUY",
                "sector": "Retailers"
            },
            {
                "navMid": -0.37,
                "navPerShare": null,
                "rsi": 57.5,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "GSK",
                "stockName": "GLAXOSMITHKLI",
                "profit": 5749,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 13.9,
                "techSum": 1,
                "percentUp": -0.74,
                "weekPercentUp": null,
                "marketCapitalisation": 80756,
                "day": "0925288",
                "week": "0925288",
                "years": "GSK",
                "sedol": "GB0009252882",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.81,
                "bullAdvice": "2021-12-22 BUY",
                "sector": "Pharmaceutica"
            },
            {
                "navMid": 0.01,
                "navPerShare": null,
                "rsi": 54.88,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SPX",
                "stockName": "SPIRAX-SARCO",
                "profit": 174,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 68.34,
                "techSum": 1,
                "percentUp": -0.9,
                "weekPercentUp": null,
                "marketCapitalisation": 11873,
                "day": "BWFGQN1",
                "week": "BWFGQN1",
                "years": "SPX",
                "sedol": "GB00BWFGQN14",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.69,
                "bullAdvice": "2022-01-04 SELL",
                "sector": "Industrial En"
            },
            {
                "navMid": 0.23,
                "navPerShare": null,
                "rsi": 53.61,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SSE",
                "stockName": "SSE",
                "profit": 2246,
                "cash": null,
                "exDividend": "2022-01-13",
                "netNet": 0,
                "peRatio": 7.52,
                "techSum": 1,
                "percentUp": -0.96,
                "weekPercentUp": null,
                "marketCapitalisation": 17144,
                "day": "0790873",
                "week": "0790873",
                "years": "SSE",
                "sedol": "GB0007908733",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.94,
                "bullAdvice": "2022-01-05 SELL",
                "sector": "Electricity"
            },
            {
                "navMid": 0.34,
                "navPerShare": null,
                "rsi": 44,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "PNN",
                "stockName": "PENNON GROUP",
                "profit": 108,
                "cash": null,
                "exDividend": "2022-01-27",
                "netNet": 0,
                "peRatio": 1.87,
                "techSum": -1,
                "percentUp": -1.09,
                "weekPercentUp": null,
                "marketCapitalisation": 4943,
                "day": "BNNTLN4",
                "week": "BNNTLN4",
                "years": "PNN",
                "sedol": "GB00BNNTLN49",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.02,
                "bullAdvice": "2021-12-24 BUY",
                "sector": "Gas, Water an"
            },
            {
                "navMid": 0.51,
                "navPerShare": null,
                "rsi": 61,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BKG",
                "stockName": "BERKELEY GP.H",
                "profit": 423,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 14.3,
                "techSum": 1,
                "percentUp": -1.1,
                "weekPercentUp": null,
                "marketCapitalisation": 5901,
                "day": "BLJNXL8",
                "week": "BLJNXL8",
                "years": "BKG",
                "sedol": "GB00BLJNXL82",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.05,
                "bullAdvice": "2021-12-31 SELL",
                "sector": "Household Goo"
            },
            {
                "navMid": -0.05,
                "navPerShare": null,
                "rsi": 63.2,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SGE",
                "stockName": "SAGE GRP.",
                "profit": 0,
                "cash": null,
                "exDividend": "2022-01-13",
                "netNet": 0,
                "peRatio": 31.96,
                "techSum": 1,
                "percentUp": -1.28,
                "weekPercentUp": null,
                "marketCapitalisation": 8978,
                "day": "B8C3BL0",
                "week": "B8C3BL0",
                "years": "SGE",
                "sedol": "GB00B8C3BL03",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.24,
                "bullAdvice": "2022-01-04 SELL",
                "sector": "Software and "
            },
            {
                "navMid": 0.5,
                "navPerShare": null,
                "rsi": 41.5,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "FRES",
                "stockName": "FRESNILLO",
                "profit": 292,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 22.97,
                "techSum": -1,
                "percentUp": -1.43,
                "weekPercentUp": null,
                "marketCapitalisation": 6305,
                "day": "B2QPKJ1",
                "week": "B2QPKJ1",
                "years": "FRES",
                "sedol": "GB00B2QPKJ12",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.3,
                "bullAdvice": "2021-12-24 BUY",
                "sector": "Precious Meta"
            },
            {
                "navMid": 0.15,
                "navPerShare": null,
                "rsi": 54,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SVT",
                "stockName": "SEVERN TRENT",
                "profit": 212,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 32.85,
                "techSum": 1,
                "percentUp": -1.67,
                "weekPercentUp": null,
                "marketCapitalisation": 7313,
                "day": "B1FH8J7",
                "week": "B1FH8J7",
                "years": "SVT",
                "sedol": "GB00B1FH8J72",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0,
                "bullAdvice": "2021-12-16 SELL",
                "sector": "Gas, Water an"
            },
            {
                "navMid": 0.38,
                "navPerShare": null,
                "rsi": 45.6,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "UU.",
                "stockName": "UTD. UTILITIE",
                "profit": 107,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 16.29,
                "techSum": -1,
                "percentUp": -1.8,
                "weekPercentUp": null,
                "marketCapitalisation": 7385,
                "day": "B39J2M4",
                "week": "B39J2M4",
                "years": "UU.",
                "sedol": "GB00B39J2M42",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.32,
                "bullAdvice": "2021-12-31 BUY",
                "sector": "Gas, Water an"
            },
            {
                "navMid": 0.25,
                "navPerShare": null,
                "rsi": 42,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "HIK",
                "stockName": "HIKMA",
                "profit": 336,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 16.35,
                "techSum": -1,
                "percentUp": -1.95,
                "weekPercentUp": null,
                "marketCapitalisation": 5071,
                "day": "B0LCW08",
                "week": "B0LCW08",
                "years": "HIK",
                "sedol": "GB00B0LCW083",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.16,
                "bullAdvice": "2021-12-29 BUY",
                "sector": "Pharmaceutica"
            },
            {
                "navMid": 0,
                "navPerShare": null,
                "rsi": 53,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "HLMA",
                "stockName": "HALMA",
                "profit": 203,
                "cash": null,
                "exDividend": "2021-12-23",
                "netNet": 0,
                "peRatio": 58.48,
                "techSum": 1,
                "percentUp": -1.99,
                "weekPercentUp": null,
                "marketCapitalisation": 11902,
                "day": "0405207",
                "week": "0405207",
                "years": "HLMA",
                "sedol": "GB0004052071",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.35,
                "bullAdvice": "2022-01-05 SELL",
                "sector": "Electronic an"
            },
            {
                "navMid": 0.33,
                "navPerShare": null,
                "rsi": 56.6,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "NG.",
                "stockName": "NATIONAL GRID",
                "profit": 1255,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 22.82,
                "techSum": 1,
                "percentUp": -2.02,
                "weekPercentUp": null,
                "marketCapitalisation": 38471,
                "day": "BDR05C0",
                "week": "BDR05C0",
                "years": "NG.",
                "sedol": "GB00BDR05C01",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.12,
                "bullAdvice": "2021-12-30 SELL",
                "sector": "Gas, Water an"
            },
            {
                "navMid": 0.01,
                "navPerShare": null,
                "rsi": 56.9,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RMV",
                "stockName": "RIGHTMOVE",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0.01,
                "peRatio": 62.1,
                "techSum": 1,
                "percentUp": -2.37,
                "weekPercentUp": null,
                "marketCapitalisation": 6722,
                "day": "BGDT3G2",
                "week": "BGDT3G2",
                "years": "RMV",
                "sedol": "GB00BGDT3G23",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.15,
                "bullAdvice": "2022-01-05 SELL",
                "sector": "Software and "
            },
            {
                "navMid": -0.15,
                "navPerShare": null,
                "rsi": 46.3,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "AZN",
                "stockName": "ASTRAZENECA",
                "profit": 2492,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 47.26,
                "techSum": -1,
                "percentUp": -2.39,
                "weekPercentUp": null,
                "marketCapitalisation": 111060,
                "day": "0989529",
                "week": "0989529",
                "years": "AZN",
                "sedol": "GB0009895292",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.05,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Pharmaceutica"
            },
            {
                "navMid": -0.1,
                "navPerShare": null,
                "rsi": 52.86,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "EXPN",
                "stockName": "EXPERIAN",
                "profit": 615,
                "cash": null,
                "exDividend": "2022-01-06",
                "netNet": 0,
                "peRatio": 55.67,
                "techSum": 0,
                "percentUp": -2.57,
                "weekPercentUp": null,
                "marketCapitalisation": 32767,
                "day": "B19NLV4",
                "week": "B19NLV4",
                "years": "EXPN",
                "sedol": "GB00B19NLV48",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.28,
                "bullAdvice": "2022-01-05 BUY",
                "sector": "Industrial Su"
            },
            {
                "navMid": 0.03,
                "navPerShare": null,
                "rsi": 48,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "AVV",
                "stockName": "AVEVA GRP",
                "profit": 0,
                "cash": null,
                "exDividend": "2022-01-06",
                "netNet": 0,
                "peRatio": 293.13,
                "techSum": -1,
                "percentUp": -2.71,
                "weekPercentUp": null,
                "marketCapitalisation": 10020,
                "day": "BBG9VN7",
                "week": "BBG9VN7",
                "years": "AVV",
                "sedol": "GB00BBG9VN75",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.45,
                "bullAdvice": "2021-12-30 SELL",
                "sector": "Software and "
            },
            {
                "navMid": -0.05,
                "navPerShare": null,
                "rsi": 49,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "BNZL",
                "stockName": "BUNZL",
                "profit": 430,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 22.29,
                "techSum": 0,
                "percentUp": -2.73,
                "weekPercentUp": null,
                "marketCapitalisation": 9682,
                "day": "B0744B3",
                "week": "B0744B3",
                "years": "BNZL",
                "sedol": "GB00B0744B38",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.6,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "General Indus"
            },
            {
                "navMid": 0.45,
                "navPerShare": null,
                "rsi": 46,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "REL",
                "stockName": "RELX",
                "profit": 1224,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 36.99,
                "techSum": 0,
                "percentUp": -2.81,
                "weekPercentUp": null,
                "marketCapitalisation": 45398,
                "day": "B2B0DG9",
                "week": "B2B0DG9",
                "years": "REL",
                "sedol": "GB00B2B0DG97",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.74,
                "bullAdvice": "2022-01-04 SELL",
                "sector": "Media"
            },
            {
                "navMid": 0.13,
                "navPerShare": null,
                "rsi": 43,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "OCDO",
                "stockName": "OCADO",
                "profit": -126,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -91.48,
                "techSum": -2,
                "percentUp": -3.12,
                "weekPercentUp": null,
                "marketCapitalisation": 12049,
                "day": "B3MBS74",
                "week": "B3MBS74",
                "years": "OCDO",
                "sedol": "GB00B3MBS747",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 3.82,
                "bullAdvice": "2021-12-21 BUY",
                "sector": "Personal Care"
            },
            {
                "navMid": -0.07,
                "navPerShare": null,
                "rsi": 33.9,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "JET",
                "stockName": "JUST EAT TAKE",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": -39.7,
                "techSum": -1,
                "percentUp": -3.2,
                "weekPercentUp": null,
                "marketCapitalisation": 8113,
                "day": "1201570",
                "week": "1201570",
                "years": "JET",
                "sedol": "NL0012015705",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": 0.03,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Software and "
            },
            {
                "navMid": 0.1,
                "navPerShare": null,
                "rsi": 50,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "ADM",
                "stockName": "ADMIRAL GRP",
                "profit": 0,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 17.11,
                "techSum": -1,
                "percentUp": -3.22,
                "weekPercentUp": null,
                "marketCapitalisation": 9124,
                "day": "B02J639",
                "week": "B02J639",
                "years": "ADM",
                "sedol": "GB00B02J6398",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -0.65,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Non-life Insu"
            },
            {
                "navMid": 0.33,
                "navPerShare": null,
                "rsi": 36,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "POLY",
                "stockName": "POLYMETAL INT",
                "profit": 847,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 7.4,
                "techSum": -1,
                "percentUp": -3.29,
                "weekPercentUp": null,
                "marketCapitalisation": 5915,
                "day": "B6T5S47",
                "week": "B6T5S47",
                "years": "POLY",
                "sedol": "JE00B6T5S470",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.72,
                "bullAdvice": "2022-01-04 SELL",
                "sector": "Precious Meta"
            },
            {
                "navMid": -0.06,
                "navPerShare": null,
                "rsi": 40.64,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "RTO",
                "stockName": "RENTOKIL INIT",
                "profit": 186,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 55.67,
                "techSum": -1,
                "percentUp": -3.36,
                "weekPercentUp": null,
                "marketCapitalisation": 10383,
                "day": "B082RF1",
                "week": "B082RF1",
                "years": "RTO",
                "sedol": "GB00B082RF11",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -2.05,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Industrial Su"
            },
            {
                "navMid": 0.04,
                "navPerShare": null,
                "rsi": 43.65,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "CRDA",
                "stockName": "CRODA INTL.",
                "profit": 202,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 63.24,
                "techSum": -1,
                "percentUp": -4.72,
                "weekPercentUp": null,
                "marketCapitalisation": 13684,
                "day": "BJFFLV0",
                "week": "BJFFLV0",
                "years": "CRDA",
                "sedol": "GB00BJFFLV09",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -1.01,
                "bullAdvice": "2022-01-04 BUY",
                "sector": "Chemicals"
            },
            {
                "navMid": 0.07,
                "navPerShare": null,
                "rsi": 66.93,
                "midPrice": null,
                "dividend": 0,
                "tickerSymbol": "SKG",
                "stockName": "SMURFIT KAP.",
                "profit": 484,
                "cash": null,
                "exDividend": "-",
                "netNet": 0,
                "peRatio": 20.27,
                "techSum": 2,
                "percentUp": -48.77,
                "weekPercentUp": null,
                "marketCapitalisation": 10796,
                "day": "B1RR840",
                "week": "B1RR840",
                "years": "SKG",
                "sedol": "IE00B1RR8406",
                "exchangeIndex": null,
                "afterTaxProfit": null,
                "netAssets": null,
                "profitPercent": null,
                "cashPercent": null,
                "changePercent": -96.6,
                "bullAdvice": "2021-12-17 BUY",
                "sector": "General Indus"
            }
        ]
    )

)
    //  return next();
});


module.exports = router;